### ISSUE TITLE
docker_containers

### ISSUE THREAD

**Issue by thoughtjigs** [ansible/ansible-modules-core#1005]
the core docker module no longer publishes ansible facts using the docker_containers variable.

**Comment by abadger** [comment]
@smashwilson: I see where we accidentally removed this here: 80aca4b9369073d7b58ff168cf4eef8bb126c2d0

@thoughtjigs: Do you know what was in the docker_containers fact before?  It doesn't look like it was the complete list of containers.  Was it the same value that's now returned in containers (containers.changed inside of the module code) it just needs to be automatically stored in a fact?

**Comment by smashwilson** [comment]
Oh, I see, interesting. Yeah, I can take a look at adding that back in.

It looks like it was only the changed containers before the refactor, but because it's a fact, I would personally expect it to be the "inspect" results for _all_ of the running containers that match, not just the ones that were changed -- the output of `get_deployed_containers()` after the state has been applied. Does that make more sense?

It'll be easy enough to put back either way, though.

**Comment by abadger** [comment]
That's what I expected too but it seems like it's not what was there before.   If get_deployed_containers() turns out to be a superset of what we would have used before then I think it's fairly safe to do that (especially if we are returning just the changed containers in a different variable now).  If it's not a superset then it's a tougher call but I'd like to hear what people using the docker module want -- I don't use it enough to form an opinion on my own.

**Comment by thoughtjigs** [comment]
@abadger @smashwilson It was only the changed containers. As that is what my playbooks are expecting returning all containers would break my playbooks. However, it is a slightly under-documented feature ... having ansible facts returned for different collections of containers would be useful. Perhaps there could be several dictionaries of facts: docker_changed, docker_running, docker_stopped. docker_containers could continue to contain only the changed docker_container facts and be deprecated in favor of the above three. 

Additionally, providing switches for container fact gathering might be useful for large container inventories ... though I have seen no performance hit when using my dynamic docker container inventory script that gathers facts on all containers. 

I could take a look at creating a patch for this as this is critical to our playbooks (I had to revert to 1.8.4 for the time being) if that would be useful. 

Thanks

**Comment by bcoca** [comment]
there is a docker_facts module in the queue, I would not overload this one with too many features (changed containers seems fine).

**Comment by gimoh** [comment]
ehm, in 1.8.4 it was actually returning inspect data for all containers that matched or matched and were running (depending on value of state option), whether their state was changed or not.  It was actually returning output of `get_deployed_containers()` or `get_running_containers()`.

See https://github.com/ansible/ansible-modules-core/compare/release1.8.4...stable-1.9?diff=split&name=stable-1.9#diff-f748aba7cf31a4ff7a2e072e813023dfL817

You can also test this using test-module, check the output [in this gist](https://gist.github.com/gimoh/78cfff0859924c21e614), note the value of `docker_containers`, `changed` and `msg`.

I'm not sure about that `docker_facts` module but in the meantime I'd vote to restore 1.8.4 functionality.

The PR #1078 implements only part of the fix (returning inspect data, but only for containers where state was changed). I can implement a fix if we can agree on this.
