### ISSUE TITLE
Error if htpasswd file includes a blank line 

### ISSUE THREAD

**Issue by xrow** [ansible/ansible-modules-core#1116]
Hi, 
I would like to reopen the following ticket https://github.com/ansible/ansible/issues/5328.

The problem is that if a htpasswd file has na empty line in the end, ansible will fail with:

TASK: [nagios | htpasswd path=/etc/nagios/passwd name=admin password=admin owner=root group=apache mode=0640] **\* 
failed: [monitoring.xrow.lan] => {"failed": true}
msg: need more than 1 value to unpack

FATAL: all hosts have already failed -- aborting

```
- htpasswd: path=/etc/nagios/passwd name=admin password=admin owner=root group=apache mode=0640
```

Contents of /etc/nagios/passwd 

```
nagiosadmin:RbdO4ou4PNyMg

```

My ansible verison is  1.9.0.1

**Comment by mscherer** [comment]
Yep, that's a issue in the underlying library IIRC. I am not sure exactly on how/what would be the right answer. Either reimplement it, or fix upstream ( https://code.google.com/p/passlib/ )

**Comment by Jmainguy** [comment]
Suppose we could have ansible sed the file first and remove any blank lines, ^$, and then run the normal python stuff. @mscherer @xrow @bcoca, what do you guys think? Worth coding in?

**Comment by xrow** [comment]
This would have worked for my case.

**Comment by Jmainguy** [comment]
@xrow give #1406 a shot

**Comment by xrow** [comment]
I thanks I will try this for sure once it is available in my version from EPEL.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

The commit a1181b490b7e00953a954878f3694a32378deca4 was recently merged in regarding this, which should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by rbu** [comment]
I opened https://bitbucket.org/ecollins/passlib/issues/73/htpasswdfile-does-not-like-empty-lines
