### ISSUE TITLE
lineinfile repeatedly inserts multiline lines

### ISSUE THREAD

**Issue by tongpu** [ansible/ansible-modules-core#118]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Ubuntu 12.04
##### Summary:

When trying to insert multiple lines by adding `\n` to the `line` argument of the lineinfile the line gets inserted every time the task is executed.
##### Steps To Reproduce:

Run the following ansible call two times

```
ansible testhost -m lineinfile -a "dest=/tmp/testfile line='first line\nsecond line' create=yes"
```
##### Expected Results:

```
tongpu@localhost:~$ ansible testhost -m lineinfile -a "dest=/tmp/testfile line='first line\nsecond line' create=yes"
localhost | success >> {
    "backup": "", 
    "changed": true, 
    "msg": "line added"
}

tongpu@localhost:~$ ansible testhost -m lineinfile -a "dest=/tmp/testfile line='first line\nsecond line' create=yes"
localhost | success >> {
    "backup": "", 
    "changed": false, 
    "msg": ""
}
```

/tmp/testfile

```
first line
second line
```
##### Actual Results:

```
tongpu@localhost:~$ ansible testhost -m lineinfile -a "dest=/tmp/testfile line='first line\nsecond line' create=yes"
localhost | success >> {
    "backup": "", 
    "changed": true, 
    "msg": "line added"
}

tongpu@localhost:~$ ansible testhost -m lineinfile -a "dest=/tmp/testfile line='first line\nsecond line' create=yes"
localhost | success >> {
    "backup": "", 
    "changed": true, 
    "msg": "line added"
}
```

/tmp/testfile

```
first line
second line
first line
second line
```

**Comment by abadger** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- lineinfile is unfortunately only intended for single lines.
  
  > This is primarily useful when you want to change a single line in a file only. See the replace module if you want to change multiple, similar lines; for other cases, see the copy or template modules.
  > - http://docs.ansible.com/lineinfile_module.html
  
  Depending on your actual use case, replace or template might do what you need.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
