### ISSUE TITLE
Modules still using BabyJSON

### ISSUE THREAD

**Issue by sivel** [ansible/ansible-modules-core#1211]
The following modules are still using BabyJSON to report errors/failures.  BabyJSON was support was removed in 1.8, so these errors will result in a parse error now.

cloud/azure/azure.py
cloud/digital_ocean/digital_ocean.py
cloud/digital_ocean/digital_ocean_domain.py
cloud/digital_ocean/digital_ocean_sshkey.py
cloud/docker/docker.py
cloud/docker/docker_image.py
cloud/google/gc_storage.py
cloud/google/gce.py
cloud/google/gce_lb.py
cloud/google/gce_net.py
cloud/google/gce_pd.py
cloud/linode/linode.py
cloud/openstack/glance_image.py
cloud/openstack/nova_compute.py
cloud/openstack/nova_keypair.py
cloud/openstack/quantum_floating_ip.py
cloud/openstack/quantum_floating_ip_associate.py
cloud/openstack/quantum_network.py
cloud/openstack/quantum_router.py
cloud/openstack/quantum_router_gateway.py
cloud/openstack/quantum_router_interface.py
cloud/openstack/quantum_subnet.py
system/selinux.py

The proper way would be to use something similar to:

```
try:
    import foo
    HAS_FOO = True
except ImportError:
    HAS_FOO = False

[SNIP]

def main():
    module = AnsibleModule(...)

    if not HAS_FOO:
        module.fail_json(msg="The foo python module is required")
```

I don't have time right now to address or test these myself, but wanted to report this.

The one thing that may present problems is where a module is using a constant or value from the import when instantiating `AnsibleModule`

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
