### ISSUE TITLE
mysql_user is unable to adjust privs on DB with dots in name

### ISSUE THREAD

**Issue by seschwar** [ansible/ansible-modules-core#1226]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9.1
configured module search path = /usr/share/ansible
```
##### Environment:

Debian unstable
##### Summary:

It is not possible with Ansible to adjust privileges on a MySQL database which
has dots in its name.  See also ansible/ansible#3767 and ansible/ansible#7769, which was fixed in ansible/ansible#7804. But the fix never got merged.
##### Steps To Reproduce:

Just run the following command on a host with MySQL running:

```
ansible -m mysql_user -a 'name=myuser priv=`a.dotted.db`.*:ALL' localhost
```
##### Expected Results:

```
localhost | success >> {
    "changed": true, 
    "user": "myuser"
}
```
##### Actual Results:

```
localhost | FAILED >> {
    "failed": true, 
    "msg": "User escaped identifiers must escape extra quotes"
}
```

**Comment by Jmainguy** [comment]
@seschwar Give PR #1358 a shot and see if that works, its a copy of @escaped's work. Seemed to work for me.

```
[root@phy01 ansible]# ansible -i hosts all -m mysql_user -a 'name=myuser priv=`a.dotted.db`.*:ALL password=neat'
ca.soh.re | success >> {
    "changed": true,
    "user": "myuser"
}

[root@phy01 ansible]# ansible -i hosts all -m mysql_user -a 'name=myuser priv=`a.dotted.db`.*:ALL password=neat'
ca.soh.re | success >> {
    "changed": false,
    "user": "myuser"
}
```

**Comment by abadger** [comment]
#1358 has been merged so closing this.  Feel free to let us know if it isn't (new bug report or ping us on IRC -- #ansible-devel on freenode, I'm abadger1999).

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
