### ISSUE TITLE
docker module: incompatible with docker-py 1.2.x

### ISSUE THREAD

**Issue by sivel** [ansible/ansible-modules-core#1227]
docker-py recently moved their constants in a backwards incompatible way in v1.2.x

Previously we accessed `docker.client.DEFAULT_DOCKER_API_VERSION`

That constant is now available at `docker.client.constants.DEFAULT_DOCKER_API_VERSION`

See https://github.com/docker/docker-py/pull/570 for the relevant change.

We will need to update reference of this constant.

cc @smashwilson @abadger

**Comment by TrustNoOne** [comment]
:+1: 
N.b.: **this bug is not related only to the constant change!**
even if I manually specify the api version, authentication doesn't work anymore!
just tried: **same exact config I had before + docker_api_version: "1.18"**, if I update the docker host to docker-py 1.2.1 I get this instead of success:

`failed: [192.168.33.10] => {"changes": ["{\"status\":\"Pulling repository ***"}\r\n", "{\"errorDetail\":{\"message\":\"Authentication is required.\"},\"error\":\"Authentication is required.\"}\r\n"], "failed": true, "status": ""}
msg: Unrecognized status from pull.`

I'm using registry v2, and docker-py 1.2 has some changes for registry v2 so it might be related to that

**Comment by settinghead** [comment]
+1

**Comment by Evilcry** [comment]
+1

**Comment by N3mes1s** [comment]
yeah +1

**Comment by RamonBeast** [comment]
+1

**Comment by daniilyar** [comment]
+1, switching to previous docker-py version (1.1.0) fixed the problem for me

**Comment by abadger** [comment]
Fixed the change in location for constants.

@TrustNoOne Could you open a separate ticket for your issue (assuming that it's still a problem)?  That seems to be a different 1.2.x problem.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by memelet** [comment]
Did this go into 1.9.2, or do we wait for 2.x?

**Comment by TrustNoOne** [comment]
It did go into 1.9.2, but now docker-py 1.3 is incompatible with ansible 1.9.2... It looks like docker-py is always ahead :D
