### ISSUE TITLE
Resolve relative paths given as arguments in custom modules

### ISSUE THREAD

**Issue by er-net** [ansible/ansible-modules-core#1245]
**Feature Idea**

When writing a custom module, it should be possible to resolve relative paths given as arguments, just as the core modules do ('src' in 'copy', for instance).

In other words, if a file exists under 'roleplay-dir/roles/x/files', acustom module should be able to obtain it when running as a task in that role.

**Comment by bcoca** [comment]
the same functions are available to all plugins, I'm not sure what you are asking for here

**Comment by er-net** [comment]
Say I'm writing a new module, and I want to have an argument which points to a file (which I'd like to read or whatever). I want it to be possible to receive an absolute path or a "relative" one (pointing to roles/x/files directory).

How can I receive such a "relative" path and resolve it to the actual file? I couldn't find a way to do that.

Moreover, I tried to run the "test-module" script on the "copy" core module (as if it was just a custom module), and it wasn't able to resolve a relative path.
Meaning, as far as I understand it, there's nothing special in the "copy" module's code, but it is being invoked in a different way (and so does all the core modules).

**Comment by bcoca** [comment]
i'm going to assume you wan the resolution to a file 'local to the master', this is achieved by having an action plugin, as modules always execute on the target machine and have no access to the controler/master. Action plugins of the same name get executed instead of the module (in the case of copy and file the action plugins then run the module if needed).

closing this as this is more a question for ansible-devel than a bug/issue
