### ISSUE TITLE
apt-get module doesn't allow regular expressions for package names

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible-modules-core#1258]
**Issue Type:**

Bug report

**Ansible Version:**

ansible 1.9.0.1

**Environment:**

Mac OSX 10.10.3
Ubuntu 15.04
Debian 8.0 Jessie

**Summary:**

Error:

```
TASK: [logging | install syslog-ng compile dependencies] **********************
failed: [192.168.4.5] => (item=build-essential,flex,bison,glib-2.0) => {"failed": true, "item": "build-essential,flex,bison,glib-2.0"}
msg: No package matching 'glib-2.0' is available
```

**Steps To Reproduce:**

run `vagrant provision` 

Basically running ansible with vagrant.

with play below:

```

---
- name: install syslog-ng compile dependencies
  apt: pkg={{ item }}
       update_cache=yes
       state=present

  with_items:
  - build-essential
  - flex
  - bison
  - glib-2.0
```

**Expected Results:**

Simply that it works. The package is available with `sudo apt-get install glib-2.0`.

**Actual Results:**

Error in steps to reproduce.

**Comment by abadger** [comment]
Searching packages.debian.org and packages.ubuntu.com, "glib-2.0" doesn't appear to be a valid package name.  Is it a virtual provide perhaps?  A name that the actual package lists in its metadata as being an equivalent of the actual package name?

If so the module is expecting the actual package name.  If someone would like to enhance the module to be able to deal with virtual provides as well, we'd review a PR for that.

**Comment by hyperfocus1338** [comment]
Yeah I noticed, couldn't find it there either, but it does exist says my package manager. I have no idea what a virtual provide is. This is the output when I do `sudo apt-get install glib-2.0` on Debian 8.0 jessie:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'gir1.2-spice-client-glib-2.0' for regex 'glib-2.0'
Note, selecting 'gobject-introspection-glib-2.0' for regex 'glib-2.0'
Note, selecting 'gir1.2-glib-2.0' for regex 'glib-2.0'
Note, selecting 'gir1.0-glib-2.0' for regex 'glib-2.0'
Note, selecting 'libqtglib-2.0-0' for regex 'glib-2.0'
Note, selecting 'libspice-client-glib-2.0-dev' for regex 'glib-2.0'
Note, selecting 'libspice-client-glib-2.0-1' for regex 'glib-2.0'
Note, selecting 'libspice-client-glib-2.0-8' for regex 'glib-2.0'
gir1.2-glib-2.0 is already the newest version.
gir1.2-glib-2.0 set to manually installed.
The following extra packages will be installed:
  dconf-gsettings-backend dconf-service glib-networking glib-networking-common glib-networking-services gsettings-desktop-schemas libasyncns0 libdconf1 libelfg0
  libflac8 libglib2.0-bin libglib2.0-dev libice6 libogg0 libopus0 libpcre3-dev libpcrecpp0 libpixman-1-0 libpixman-1-dev libpolkit-gobject-1-0 libproxy1
  libpthread-stubs0-dev libpulse-mainloop-glib0 libpulse0 libqtcore4 libsm6 libsndfile1 libsoup2.4-1 libspice-protocol-dev libspice-server-dev libspice-server1
  libssl-dev libssl-doc libusb-1.0-0 libusbredirhost1 libusbredirparser1 libvorbis0a libvorbisenc2 libx11-6 libx11-data libx11-dev libx11-doc libx11-xcb1 libxau-dev
  libxau6 libxcb1 libxcb1-dev libxdmcp-dev libxdmcp6 libxext-dev libxext6 libxi6 libxinerama-dev libxinerama1 libxtst6 pkg-config qtcore4-l10n
  spice-client-glib-usb-acl-helper x11-common x11proto-core-dev x11proto-input-dev x11proto-kb-dev x11proto-xext-dev x11proto-xinerama-dev xorg-sgml-doctools
  xtrans-dev zlib1g-dev
Suggested packages:
  libglib2.0-doc opus-tools pulseaudio libthai0 libxcb-doc libxext-doc
The following NEW packages will be installed:
  dconf-gsettings-backend dconf-service gir1.2-spice-client-glib-2.0 glib-networking glib-networking-common glib-networking-services gsettings-desktop-schemas
  libasyncns0 libdconf1 libelfg0 libflac8 libglib2.0-bin libglib2.0-dev libice6 libogg0 libopus0 libpcre3-dev libpcrecpp0 libpixman-1-0 libpixman-1-dev
  libpolkit-gobject-1-0 libproxy1 libpthread-stubs0-dev libpulse-mainloop-glib0 libpulse0 libqtcore4 libqtglib-2.0-0 libsm6 libsndfile1 libsoup2.4-1
  libspice-client-glib-2.0-8 libspice-client-glib-2.0-dev libspice-protocol-dev libspice-server-dev libspice-server1 libssl-dev libssl-doc libusb-1.0-0
  libusbredirhost1 libusbredirparser1 libvorbis0a libvorbisenc2 libx11-6 libx11-data libx11-dev libx11-doc libx11-xcb1 libxau-dev libxau6 libxcb1 libxcb1-dev
  libxdmcp-dev libxdmcp6 libxext-dev libxext6 libxi6 libxinerama-dev libxinerama1 libxtst6 pkg-config qtcore4-l10n spice-client-glib-usb-acl-helper x11-common
  x11proto-core-dev x11proto-input-dev x11proto-kb-dev x11proto-xext-dev x11proto-xinerama-dev xorg-sgml-doctools xtrans-dev zlib1g-dev
0 upgraded, 71 newly installed, 0 to remove and 15 not upgraded.
Need to get 20.7 MB of archives.
After this operation, 73.1 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

I did find https://packages.debian.org/source/jessie/glib2.0, which also appears to be working.. `sudo apt-get install glib2.0` gives me the same output above.

Edit:

Just tried:

```
- name: install syslog-ng compile dependencies
  apt: pkg={{ item }}
       update_cache=yes
       state=present

  with_items:
  - build-essential
  - flex
  - bison
  - glib2.0
```

Which gives the error below:

```
TASK: [logging | install syslog-ng compile dependencies] **********************
failed: [192.168.4.7] => (item=build-essential,flex,bison,glib2.0) => {"failed": true, "item": "build-essential,flex,bison,glib2.0"}
msg: No package matching 'glib2.0' is available
```

**Comment by abadger** [comment]
Yeah, so under the hood, the apt-get commandline is doing something different than what our usage of the python-apt API is.  For the glib2.0 case, I'm guessing that apt-get might be retrieving information about the source package, then looking up the binary packages that get built from that.  And then installing all of those binary packages.

For the glib-2.0 case I don't know what apt could be doing since that doesn't match with any package names that I can find :-(

The workaround for now would be to use the actual binary package name that you are interested in rather than names that apt-get is performing some sort of pre-processing on.  Like libglib2.0-0 for the runtime library or libglib2.0-dev for the glib header files.

Since it looks like your goal is to install the packages needed to compile syslog-ng, it might also be easier to do:

```
- apt:
    pkg: syslog-ng
    state: build-dep
```

**Comment by abadger** [comment]
After talking to some apt developers it looks like apt is doing a regex match (thus the messages like "Note, selecting 'gir1.0-glib-2.0' for regex 'glib-2.0'" in the apt-get output) if it can't find a packagename.  Re-reading the output we're getting from apt with that in mind, it looks like specifying "glib-2.0" as the packagename is only getting glib2.0-0 and glib2.0-dev installed indirectly because it's a dependency of some of the packages that match the regex.  The upstream devs noted that this is something of a historical wart in apt-get's command line UI and it might be better for ansible to enable regex installing via a different parameter (so pkg would be exact matches on pkgname and pkg_regex would be regular expression matches).

Looking into what that would look like now.

**Comment by abadger** [comment]
Talked this through with other ansible devs and we don't think we'll implement regex matching at this time.  Here's what we're thinking:
- We agree with the upstream apt developers that implicit regex matching is a UI bug rather than a feature.  It leads to situations like this one where you think you're installing a package named "glib2.0" but really you're installing a set of packages whose names match a regex constructed from that string.  At best, this does what you intended but also installs a bunch of unrelated packages.  At worst, it installs a bunch of unrelated packages without pulling in the package you actually wanted via a dependency.
- Apt-get mitigates this by (1) displaying a warning message about finding packages via regex and (2) prompting the user to confirm that this is what they want to do.  Ansible doesn't have the option to print a warning or the option to prompt before installing.
- In the cases where you actually do want to use a wildcard match, Ansible allows explicit fnmatch patterns.  So you can do `name="*glib2.0*"` if that's what you really mean.

I will update the apt module documentation to warn people of this difference with apt-get's behaviour and point out fnmatch patterns as an alternative.

**Comment by abadger** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- That ansible is not installing a package that apt-get would install

However, however what is happening is that:
- apt-get is actually doing an implicit regular expression match on the package name string and then installing a large set of packages that you didn't actually want.  Among this set of packages, some of them have a dependency on the package you do want so the package you want is being installed as well.

We would suggest:
- For this specific case, using the build-dep state is probably what you want:

```
- apt:
    pkg: syslog-ng
    state: build-dep
```

  For the general case of installing a package you'd either want to use the package's actual name or an fnmatch wildcard pattern rather than an implicit regex.  You can find the fnmatch syntax in the python stdlib documentation: https://docs.python.org/2/library/fnmatch.html

Using this bug as an example, you could do either of the following:

```
# Only install the library you actually want
- apt:
  pkg:  libglib2.0-0
  state: present

# Install packages whose name contains "glib-2.0", similar to what apt-get install does
- apt:
  pkg: "*glib-2.0*"
  state: present
```

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by hyperfocus1338** [comment]
Thank you for your research and explanation. I was also currently also bypassing the issue with simply:

```
- name: install glib
  command: apt-get install glib-2.0 -y
```

However I haven't been able to succesfully automate the compilation of syslog-ng yet, the glib-2.0 dependency isn't recognized while trying to compile. But it's not an ansible issue. 

I'll look into this when I have more time. But with this information I'll figure it out, thanks!
