### ISSUE TITLE
mysql_user: check_implicit_admin vs documentation

### ISSUE THREAD

**Issue by karpy47** [ansible/ansible-modules-core#1266]
Documentation says: 
"Both C(login_password) and C(login_username) are required when you are
     passing credentials. If none are present, the module will attempt to read
     the credentials from C(~/.my.cnf), and finally fall back to using the MySQL
     default login of 'root' with no password."

However this is only true if the option "check_implicit_admin" is used, otherwise the last resort of "root" + no password is never reached.

This might have been intended, but please update docs.

**Comment by blackreed9** [comment]
While looking at this I found that the check_implicit_admin value, which is treated as a boolean, is not typed or documented as one.

argument_spec() entry:

```
check_implicit_admin=dict(default=False)
```

what I think we want:

```
check_implicit_admin=dict(type="bool",  default="no")
```

Either way I suggest the _Options_ section be updated with a _choices_ entry as well as updating the _Note_ ( let me know )

I have a PR for the documentation update ready to go, but then I tripped over the argument type change.  Since this issue is flagged for documentation I wasn't sure what the policy was for making non-doc changes in a documentation Issue.  If you prefer I can open another Issue against the code change and create a second PR.
