### ISSUE TITLE
Modules with "old" style module_utils imports

### ISSUE THREAD

**Issue by sivel** [ansible/ansible-modules-core#1351]
The following modules are using the "old" style module import `#<<INCLUDE_ANSIBLE_MODULE_COMMON>>` instead of `from ansible.module_utils.basic import *`
- cloud/amazon/_ec2_ami_search.py
- cloud/vmware/vsphere_guest.py
- files/replace.py

**Comment by abadger** [comment]
Thanks for checking for these old code styles @sivel!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
