### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by sameergautam** [ansible/ansible-modules-core#1376]
I am writing in reference to the ec2_ami_find module. The documentation says

```
ami_tags
```

However, the following example in the documentation uses only 

```
tags
```

So update the documentation accordingly.

**Comment by Jmainguy** [comment]
#1389 has been created to fix this issue. @sameergautam on a side note, the documentation is generated from the code on github, you can create a PR to fix an easy one like this. Thank you for reporting this error.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
