### ISSUE TITLE
mysql user fails when the hostname has capital letters

### ISSUE THREAD

**Issue by muelli** [ansible/ansible-modules-core#1386]
According to https://github.com/debops/debops/issues/113, a puppet-esque workaround would be for ansible to lower the hostname before entering it into the database. Right now, neither `user_exists` nor `user_add` do not lower the hostname: https://github.com/ansible/ansible-modules-core/blob/devel/database/mysql/mysql_user.py#L210

**Comment by Jmainguy** [comment]
So it creates the user using lowercase already, but it doesn't check if the lowercase name is created already, so it tries to create it again on subsequent runs. The fix will be to change the checking portion of the code, user_exists presumably. This was tested on centos6.

```
[root@phy01 ansible]# ansible -i hosts -m mysql_user -a "name=jon host=JON.SOH.RE password=neat" all
ca.soh.re | success >> {
    "changed": true,
    "user": "jon"
}

[root@phy01 ansible]# ansible -i hosts -m mysql_user -a "name=jon host=JON.SOH.RE password=neat" all
ca.soh.re | FAILED >> {
    "failed": true,
    "msg": "(1396, \"Operation CREATE USER failed for 'jon'@'jon.soh.re'\")"
}

[root@phy01 ansible]# ansible -i hosts -m mysql_user -a "name=jon host=jon.soh.re password=neat" all
ca.soh.re | success >> {
    "changed": false,
    "user": "jon"
}
```

**Comment by Jmainguy** [comment]
@muelli give #1390 a shot and see if it works for you.

Seems to work for me on centos now.

```
[root@phy01 ansible]# ansible -i hosts -m mysql_user -a "name=jon host=JON.SOH.RE password=neat state=present" all                                                                            
ca.soh.re | success >> {
    "changed": true,
    "user": "jon"
}

[root@phy01 ansible]# ansible -i hosts -m mysql_user -a "name=jon host=JON.SOH.RE password=neat state=present" all
ca.soh.re | success >> {
    "changed": false,
    "user": "jon"
}
```

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
