### ISSUE TITLE
ec2_vol errors when attaching a volume from a snapshot

### ISSUE THREAD

**Issue by lorin** [ansible/ansible-modules-core#139]
**Issue type:**

Bug report

**Ansible Version:**

1.6.2

**Environment:**

Mac OS X 10.9.3

**Summary:**

ec2_vol module fails to create a new volume from a snapshot and attach to an image, returning an error message that doesn't make sense given the arguments.

**Steps to reproduce:**
1. Start an instance on EC2, record the instance id
2. Create a new snapshot on EC2, record the snapshot id
3. Use the ec2_vol module to attach:
   
   ```
   ansible localhost -m ec2_vol -a "instance=i-123456 snapshot=snap-abcdef"
   ```

**Expected results:**

Creates a new EBS volume from the snapshot, attaches volume to the instance.

**Actual results:**

```
$ ansible localhost -m ec2_vol -a "instance=i-123456 snapshot=snap-abcdef"
localhost | FAILED >> {
    "failed": true,
    "msg": "Cannot specify volume_size and either one of name or id"
}
```

The error makes no sense, given that neither volume_size, name, nor id are arguments.

Note that the documentation for ec2_vol has an example with this exact combination of arguments, so I assume this is legal. From the docs:

```
# Example using snapshot id
- local_action:
    module: ec2_vol
    instance: XXXXXX
    snapshot: "{{ snapshot }}"
```

**Comment by lorin** [comment]
Not sure why the bot triggered, the report appears to conform to the template.

**Comment by dannyman** [comment]
With:

ec2_vol: region="{{region}}" device_name=sdd instance=i-xxxxxxxx snapshot=snap-xxxxxxxx

I get:

msg: You must specify an existing volume with id or name or a volume_size

I have written a script to do "aws ec2 create-volume" and then "aws ec2 attach-volume" since that AWS CLI seems to imply it is a two-step process.  I can't re-create this sequence with ec2_vol since I can not specify availability zone which is required in the AWS CLI create volume step.  The implication here is that availability zone will be derived from instance id so I don't see any way to clone a volume from a snapshot with this module.  :/

**Comment by eeroniemi** [comment]
FYI I created PR to get this bug fixed on current devel branch - https://github.com/ansible/ansible-modules-core/pull/1747
