### ISSUE TITLE
Git Module StrictHostKeyChecking

### ISSUE THREAD

**Issue by jody-frankowski** [ansible/ansible-modules-core#1410]
I think the git module should have the ssh option StrictHostKeyChecking default to "yes" instead of "ask". Instead of the module hanging and having users check the module documentation, we could have ansible issue a warning/error.
The option "accept_hostkey" would of course stay.
What do you think?

**Comment by bennojoy** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

The default was made to 'ask' for security reasons, so that you don't end up cloning your repo from another host.
Also This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by jody-frankowski** [comment]
It wasn't a question but a suggestion.
The module would still be secure. Take the case where StrictHostKeyChecking defaults to yes:
- If ssh knows the host key: all is good, security is ensured.
- If ssh doesn't know the host key:
  - If accept_hostkey equals to no (default): ssh won't accept the host key. Ansible can issue a warning. Security is ensured. All is fine.
  - If accept_hostkey equals to yes: ssh will accept the host key. Since it's not the default, ansible can assume the user knows what he is doing.

There is no _valid_ reasons to have the git module hang. I almost consider ansible actual behavior as a bug.
Further discussions in mailing list.
