### ISSUE TITLE
synchronize: when any inventory host matches localhost, rsync tries to connect to localhost

### ISSUE THREAD

**Issue by maria** [ansible/ansible-modules-core#1492]
## Problem
- I have a playbook `deploy.yml`:

``` ansible

- hosts: my-host

  vars:
     remote_dir: /downloads/app
     tmp_dir: /tmp

  tasks:
      - name: Copy app from local to my remote host
        synchronize: src={{ remote_dir }} dest={{ tmp_dir }}

```
- I have the inventory `hosts.ini`

```
[a-web-server]
mywebserver.com

[my-build-server]
localhost

[my-host]
myhostisawesome.com ansible_ssh_user=root
```
- When I run the playbook:

`ansible-playbook deploy.yml -i hosts.ini`

it fails with the error:

```
<127.0.0.1> ESTABLISH CONNECTION FOR USER: root
<127.0.0.1> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/var/lib/jenkins/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'mkdir -p /tmp/ansible-tmp-1433777430.66-184203194745871 && echo /tmp/ansible-tmp-1433777430.66-184203194745871'
EXEC previous known host file not found for 127.0.0.1
fatal: [myhostisawesome.com -> 127.0.0.1] => SSH Error: Host key verification failed.
    while connecting to 127.0.0.1:22
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

FATAL: all hosts have already failed -- aborting
```
- doing rsync in shell it's ok, if I remove `localhost` from my inventory works. So, even if it shouldn't match the host it does.

**Comment by bennojoy** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

it if failing on host key verification because it is trying to ssh to the localhost. if you dont want that behaviour in the inventoruy add localhost ansible_connection=local

Also this appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by maria** [comment]
Hi,

Well, why does it try localhost since I defined my playbook host to be another remote machine in another inventory group? It shouldn't try to connect to localhost since the groups are different.

**Comment by bennojoy** [comment]
@maria can you please try adding mode=pull
