### ISSUE TITLE
command module nonworking

### ISSUE THREAD

**Issue by zystem** [ansible/ansible-modules-core#1493]
my playbook

```
- hosts: all
  gather_facts : no
  tasks:
  - command: uname
```

Then I execute it I has error

```
failed: [myhost.mydomain] => {"failed": true}
msg: this module requires key=value arguments (['uname'])

FATAL: all hosts have already failed -- aborting
```

**Comment by bennojoy** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

can you please try it on the stable branch 1.9.1 

Also this appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!

**Comment by zystem** [comment]
Thank you.
In 1.9.1 issue fixed.

**Comment by bennojoy** [comment]
Hi!

This has been merged in, and will also be included in the next major release.

If you or anyone else has any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
