### ISSUE TITLE
apt module: update_cache=yes does nothing

### ISSUE THREAD

**Issue by Bengrunt** [ansible/ansible-modules-core#1497]
Hello,
I was trying to use the update_cache feature of the apt module to run apt-get update without installing a package. So I've got this basic task:

```
- name: Updating APT cache
   apt: update_cache=yes
```

When the task runs, it says 'ok' but the cache isn't updated at all.
There seem to be the same behavior if update_cache=yes is added with an actual package installation.

I'm using ansible v1.9.1 on CentOS 7 to manage hosts running Ubuntu 14.04LTS.

**Comment by cloudnull** [comment]
Bump, this issue looks like it effects all current v1.9.x versions including v1.9.2-0.1.rc1: 
- https://github.com/ansible/ansible-modules-core/blob/016ad8a1cb29d54353d14503fc07c7f98c4cb853/packaging/os/apt.py#L558-L589
- https://github.com/ansible/ansible-modules-core/blob/d56c219a158b4893303f126c5e3dfba89e908cd8/packaging/os/apt.py#L558-L589

**Comment by Bengrunt** [comment]
Hey there,

Thanks for the fix :) :+1: 

Could be nice to also add the default value for `cache_valid_time` in the [docs](http://docs.ansible.com/apt_module.html). Was wondering what it was when trying to use it earlier.

**Comment by cloudnull** [comment]
@Bengrunt  I updated the PR to now document that the `cache_valid_time` is 0 by default.

**Comment by Bengrunt** [comment]
Awesome :)
I think it's gonna help a lot of people.

**Comment by wysekm** [comment]
Hi,

I have a similar problem in Ansible 1.9.3. When I start a fresh instance in AWS EC2 and try to install packages (Ubuntu 14.04) using:

```
- name: Install packages
    apt: pkg={{item}} state=present update_cache=True
    with_items:
    - python-virtualenv
    ...
```

It always fails on the first try with saying:

```
msg: No package matching 'python-virtualenv' is available
```

When I start that playbook the second time from that task it succeeds. If I run:

```
- name: Manually update packages list
    apt: update_caches=True
```

it does nothing and the package list is not refreshed. The only scenario when refreshing packages works on the first try is when I run it explicitly:

```
- name: Manually update packages list (problem with update_cache)
    command: apt-get update
```

**Comment by cloudnull** [comment]
@wysekm if you don't mind pulling in a patch, this change fixed the issue for us https://github.com/ansible/ansible-modules-core/pull/1517 -- it's currently a pending PR to core.

**Comment by FlorinAndrei** [comment]
Same issue with 1.9.4, running on Mac, with Ubuntu 14.04 instances

**Comment by jctanner** [comment]
The apt module has undergone a few revisions since 1.9.1 and the cache updating mechanisms have been port of those revisions.

If the system does not have python-apt, the module will attempt to run 'apt-get update && apt-get install python-apt -y -q' before proceeding to evaluate the rest of the module args. That command could alter the expected timestamp on the cache because it doesn't track the previous timestamp.

If python-apt was installed, the module then does a stat on /var/lib/apt/periodic/update-success-stamp. Failing that, a stat is done on /var/lib/apt/lists. If a timestamp is obtained and the current time is less than the timestamp + the cache valid time, apt.cache.update() is called. The update() returns True, and will cause the timestamp on /var/lib/apt/lists to change. The call to .update is tracked by the 'cache_updated' key in the results dictionary but does not factor into the overall change state of the module. 

The current behavior described above seems logical as the module is intended to install packages and updating the cache is a tangential feature. If someone disagrees with that logic, we are open to changing it but would require that to go through the ansible proposals process.

If you believe this ticket is not resolved, or have further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments on closed tickets, though the mailing list is a great way to get involved or discuss this one further.

Thanks!

**Comment by cloudnull** [comment]
@jctanner I don't believe this issue should be closed as this is still a problem. If you or the core team have time I'd appreciate review on [ https://github.com/ansible/ansible-modules-core/pull/1517 ]. That pr has been in limbo for some time without review and actually addresses this issue by properly capturing the apt update time.
