### ISSUE TITLE
When using exact_count no check for count_tag

### ISSUE THREAD

**Issue by hurleyit** [ansible/ansible-modules-core#15]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.6.10
##### Environment:

N/A
##### Summary:

I was bit by the bug mentioned here: https://www.mail-archive.com/ansible-project@googlegroups.com/msg07937.html

Basically, there doesn't seem to be a requirement for count_tag when using exact_count. I don't see a bug report for this, thus adding it here.

What appears to happen currently is that if count_tag isn't specified, all (or many) ec2 instances match and it starts making api calls to terminate those instances. This was unexpected.
##### Steps To Reproduce:

Use ec2 and have an exact_count but no count_tag
##### Expected Results:

Failure because count_tag is required for exact_count
##### Actual Results:

Random termination of instances.

**Comment by jimi-c** [comment]
Hi @hurleyit, this was addressed in https://github.com/ansible/ansible/issues/9431, and this will be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by raags** [comment]
We got bit by this bug today. We are on version 1.7.2. 
This is a major issue that could affect lot of folks on ansible version older than 1.8. Can we backport this to older releases? Or at lest issue an advisory asking users to upgrade?
