### ISSUE TITLE
module ini_file replaces array values (eg. for php)

### ISSUE THREAD

**Issue by mblaschke** [ansible/ansible-modules-core#1500]
PHP allows [array values in .ini files](http://php.net/manual/en/function.parse-ini-file.php#refsect1-function.parse-ini-file-examples)

Content of file before provision:

```
[section]
foobar[] = 'foo'
foobar[] = 'bar'
foobar[] = 'baz'
```

Content after provision:

```
[section]
foobar[] = 'baz'
```

This substituation is made even if the ini-section is NOT changed :(

**Comment by bcoca** [comment]
This is a limitation of python's configparser (the python ini module), since ini is not a standard it has been implemented different incompatible ways.

The reason it always changes this sections is because the module reads and rewrites the whole file on any change, which will leave out parts configparser does not recognize.

I recommend you switch to use the template module instead.
