### ISSUE TITLE
get_url, connection refused and redirects

### ISSUE THREAD

**Issue by ashemedai** [ansible/ansible-modules-core#1574]
Something that caused me some head scratching until I debugged it via 'command: curl' is that get_url of a http URL might lead, like in my case, to a 301 redirect, to a 302 redirect, to a https URL. Which, when only specifying the http_proxy environment leaves one bewildered why you are getting a '111 Connection refused' when the http proxy is specified and known working.

I am not sure what the best way to deal with this is:
- document to always require both http_proxy and https_proxy for scenarios like this?
- augment Ansible's error reporting, maybe with a pointer about http to https redirects?
- file issue upstream for urllib fixing?

**Comment by abadger** [comment]
From the sounds of it, I don't think we can detect that a missing https_proxy setting is the reason that we're failing here but it does seem reasonable to include a small note in the documentation that a redirect can convert a http request into an https request so setting up both proxies is a good idea.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
