### ISSUE TITLE
mysql_user requires a mysql database, which does not exist on fresh ubuntu install

### ISSUE THREAD

**Issue by alexgarel** [ansible/ansible-modules-core#165]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7.2
##### Environment:

Ubuntu 14.04.1 LTS
##### Summary:

The mysql_user module tries to connect to a "mysql" database which does not necesarly exists on a fresh installed machine.
##### Steps To Reproduce:
- name: Ensure mysql-server is at the latest version
  apt: name=mysql-server state=latest
  sudo: yes

On a fresh ubuntu machine use this tasks:

```
- name: Ensure libmysqlclient-dev is at the latest version
  apt: name=libmysqlclient-dev state=latest
  sudo: yes

- name: Ensure python-mysqldb is at the latest version
  apt: name=python-mysqldb state=latest
  sudo: yes

- name: Update MySQL root user password initially
  mysql_user: >
    check_implicit_admin=True
    name=root
    password='{{ db_root_user_passwd }}'
  sudo: yes
```
##### Expected Results:

mysql shall just connect to server and add a user, no need to have a mysql database.
##### Actual Results:

```
TASK: [mysql_base | Update MySQL root user password initially] **************** 
failed: [xxxxx] => {"failed": true}
msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
```

I inspected the python exception and it says : (1049, "Unknown database 'mysql'")

in fact "mysql" is hard coded in connect function of sql_user. See https://github.com/ansible/ansible-modules-core/blob/devel/database/mysql_user.py#L386

I had to add a mysql database on the host by myself.

**Comment by alexgarel** [comment]
Resolution suggestion: make database a parameter.

**Comment by alexgarel** [comment]
@marktheunissen maybe you can explain why you choose to connect to 'mysql' or why it should exists.

**Comment by Jmainguy** [comment]
@alexgarel On a fresh install of ubuntu 1404, using latest devel ansible code, and installing mysql-server via ansible apt: module, I am unable to reproduce your issue.

the mysql db is create by default on a fresh installation of mysql, it holds the user database which lets users login, one should not remove the mysql db ever.

I used the following playbook to test this case.

---
- name: install mysql user
  apt: name=mysql-server state=latest
- name: Start the new server
  service: name=mysql state=started
- name: Ensure python-mysqldb is at the latest version
  apt: name=python-mysqldb state=latest
- name: Create a user named Jon
  mysql_user: name=Jon password=ubuntu
- name: Update MySQL root user password initially
  mysql_user:
    login_password='ubuntu'
    login_user=root
    check_implicit_admin=True

# 

On subsequent runs, I had to add the login_user and password, since we had now set it.

```
login_password='ubuntu'
login_user=root
```

**Comment by alexgarel** [comment]
Ok @Jmainguy, sorry I was wrong.

The problem is that my playbook was moving files from var/mysql to home/mysql but refactoring it, I removed a mysql restart handler, so the thing was done wrong, and loosed the mysql database in the process !

So we can reject the bug. May I open a bug so that the error message add the occuring exception. This would help understanding why the connect failed (ansible was telling me it can't connect but I didn't now this was because of mysql database missing).

**Comment by Jmainguy** [comment]
Yeah there have been a few tickets opened on dealing with the error messages from mysql, that might not be a bad one to open.

**Comment by alexgarel** [comment]
Ok I made the bug #173.
