### ISSUE TITLE
Regression: ec2_vpc

### ISSUE THREAD

**Issue by dopry** [ansible/ansible-modules-core#1686]
@abadger, you missed the if None check on subnets that was holding #825. I just found the regression tonight amidst a security update of a client's production environment.  had to rollback ansible to make things happy.

If you do not specify subnets as per http://docs.ansible.com/ec2_vpc_module.html you get the following error...

```
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1436319866.94-110176155685100/ec2_vpc", line 2436, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1436319866.94-110176155685100/ec2_vpc", line 624, in main
    (vpc_dict, new_vpc_id, subnets_changed, changed) = create_vpc(module, vpc_conn)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1436319866.94-110176155685100/ec2_vpc", line 511, in create_vpc
    for idx, val in enumerate(subnets):
TypeError: 'NoneType' object is not iterable
```

in the strictest sense it does not update existing subnets, so at least I didn't overwrite all the subnets in the environment I was working on tonight.

**Comment by abadger** [comment]
Apologies, it looks like the regression was fixed in edf1ac1ea6ffd5d44bb2bb62ad320364baf310a3 but not merged to the stable branch for release.  Pulled it into stable-1.9 now for release in 1.9.3.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
