### ISSUE TITLE
get_url does not support TLS 1.2 only server

### ISSUE THREAD

**Issue by ktarplee** [ansible/ansible-modules-core#1695]
urllib2 from python seems to work however get_url does not work.  I had to revert to shelling out to curl to fetch the file.

"Request failed: <urlopen error [Errno 1] _ssl.c:510: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version>", "state": "absent", "status_code": -1,

**Comment by bcoca** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by abadger** [comment]
@ktarplee Do you know of a public server that only supports tls 1.2?  I can set one up but if you know of one that would save me some time in identifying the problem here.

**Comment by abadger** [comment]
@ktarplee Looking through the code for a different issue, I think I found the problem.  python < 2.7.9 only lets you select which SSL/TLS protocol versions to use in two ways: either select a specific version or select the highest shared protocol among tlsv1.0, sslv3, and sslv2.  Last year we wanted to disable sslv2 and sslv3 as it was vulnerable to attack.  At the time the only way to do that was to select the specific protocol version to use instead so we chose tlsv1.0.

In python-2.7.9 some additions to the python stdlib's ssl module should make it possible to remove the SSL protocols from consideration when negotiating so I should be able to fix the code so that tls-1.1 and tls-1.2 are negotiated properly.  However, it looks like tls-1.1 and tls1.2 were also added to the stdlib in 2.7.9.  So when I fix this you'll still need to have a new enough python version on the machine you're running get_url from in order to have tls-1.2 supported.

**Comment by abadger** [comment]
Okay, I think that commit should fix this if you have pyhton-2.7.9 or above.

**Comment by ktarplee** [comment]
I am running ubuntu 14.04 on the servers that has Python version 2.7.6.  It also has python 3.4.0 available.  Can I use python3 with ansible vis the "ansible_python_interpreter" host variable?

**Comment by abadger** [comment]
@ktarplee Unfortunately no. At some point we'll be able to port the ansible controller code to python3 (/usr/bin/ansible, /usr/bin/ansible-playbook, and the libraries supporting it) but the modules (which run on the client machines) is going to be much tougher since they also have to work on python-2.4 (there's just too wide a range of hosts to be managed out there in the wild).

There are a few workarounds (of which, just using the command module with curl or wget may be the best one) but we've also started discussing whether we need to prevent people from using sslv2 and sslv3 on our side.  Those two protocols are broken but perhaps it isn't our responsibility to disallow those -- it's the responsibility of the server owners to turn them off instead.  If we don't write code that prevents those from being used then we can let openssl be responsible for negotiating the protocol version to use and if we do that, tls-1.1 and tls-1.2 will be available if the operating system's openssl library supports it.  There's an implementation of a compromise solution here: https://github.com/ansible/ansible/pull/11603 that tries to detect if the underlying openssl supports tls-1.1 and tls-1.2 and if so does just that.  We're discussing whether that's the proper way to go or if it's better to make this explicit in some way -- give modules like get_url a parameter to enable extra protocol versions if openssl supports them.

**Comment by abadger** [comment]
@ktarplee Okay, I've merged https://github.com/ansible/ansible/pull/11603  that should make tls-1.1 and tls-1.2 available as long as the OS's openssl library supports them.  The drawback of 11603 is that it also allows sslv2 and sslv3 (both insecure) if the server you're talking to doesn't support any better protocol than that.  We decided that it's the best compromise that we can make and hopefully there aren't many servers in actual use that don't support tls at all.

These fixes have gone to both the devel branch and stable-1.9 branch so they should be in the next release that we make.  you can try it out early by checking out from github or downloading the file that implements the fix and putting it into your existing ansible-1.9.2 install.  https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
