### ISSUE TITLE
get_url does not support SNI

### ISSUE THREAD

**Issue by therealmarv** [ansible/ansible-modules-core#1716]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2
##### Ansible Configuration:

Nothing changed in Ansible configuration.
##### Environment:

Host OS: OS X 10.10.4

Target OS for Ansible: Ubuntu 14.04 LTS
##### Summary:

SSL certification validation fails for certain HTTPS links (like Scala here) in comparison to standard wget and curl.
##### Steps To Reproduce:

Download current Scala with Ansible and `get_url`. Use e.g. this in your playfile:

```
- name: Download Scala package
  get_url: url=https://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.deb dest=/tmp/scala.deb
```
##### Expected Results:

Ansible will make sure that the SSL certificate is valid and (when yes) downloads file in the same way as standard curl and wget will do.

curl example which works:

```
curl -o scala.deb https://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.deb
```

wget example which works:

```
wget https://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.deb
```
##### Actual Results:

Ansible output:

```
<192.168.232.102> ESTABLISH CONNECTION FOR USER: vagrant
<192.168.232.102> REMOTE_MODULE get_url url=https://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.deb dest=/tmp/tmp.vXhrRcG15U/scala.deb
<192.168.232.102> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/marvin/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o IdentityFile="/Users/marvin/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 192.168.232.102 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436694571.93-36020544874231 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436694571.93-36020544874231 && echo $HOME/.ansible/tmp/ansible-tmp-1436694571.93-36020544874231'
<192.168.232.102> PUT /var/folders/qq/rfxw8zms5w3_btlzbhvl70rc0000gn/T/tmppSMaUn TO /home/vagrant/.ansible/tmp/ansible-tmp-1436694571.93-36020544874231/get_url
<192.168.232.102> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/marvin/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o IdentityFile="/Users/marvin/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 192.168.232.102 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=omulmwsrnpntcyyxwxbumqdobqldpuet] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-omulmwsrnpntcyyxwxbumqdobqldpuet; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1436694571.93-36020544874231/get_url; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1436694571.93-36020544874231/ >/dev/null 2>&1'"'"''
failed: [192.168.232.102] => {"failed": true}
msg: Failed to validate the SSL certificate for downloads.typesafe.com:443. Use validate_certs=False (insecure) or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible

FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment]
did you execute the curl/wget from the target machine on which get_url runs?

also can we get an dump from `openssl s_client -connect downloads.typesafe.com:443` from the server on which get_url runs?

**Comment by therealmarv** [comment]
Yes. I've executed the curl and wget commands always on the target machine. There are no warnings or error messages and no redirects.

The command `openssl s_client -connect downloads.typesafe.com:443` on the target machine shows me this:

```
vagrant@vagrant-ubuntu-trusty-32:~$ openssl s_client -connect downloads.typesafe.com:443
CONNECTED(00000003)
3073967804:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:770:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 295 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```

This output from your openssl command seems strange for me because wget and curl should also have warned me if the CA is wrong or absent. So I suspect that wget and curl do more than this openssl command.

I also checked the CA from HTTPS `downloads.typesafe.com` by an external service here http://www.networking4all.com/en/support/tools/site+check/
and it shows me that the website certficate is valid and signed:  
![image](https://cloud.githubusercontent.com/assets/1050582/8639102/ce4b7d0c-28cf-11e5-96aa-9ad7c39bd256.png)

**Comment by therealmarv** [comment]
sorry, here also the openssl command from my host machine (OS X):

```
$ openssl s_client -connect downloads.typesafe.com:443
CONNECTED(00000003)
20610:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.30.1/src/ssl/s23_clnt.c:593:
```

**Comment by bcoca** [comment]
running 
`openssl s_client -connect downloads.typesafe.com:443 -servername downloads.typesafe.com`
confirms this is an SNI issue

**Comment by abadger** [comment]
python's urllib doesn't support SNI until 2.7.9 and even there it needs some application code changes to work.  I can update our code but I'm not sure how useful that will be since so many systems are on python < 2.7.9.... @therealmarv - will it help you specifically if I do this?

**Comment by therealmarv** [comment]
In my case it will help me because I'm using Homebrew's python 2.7.x which is always the latest (currently python 2.7.10). I think it is a good approach to support it when the underlying infrastructure (Python) will also support it.

Maybe this is useful for somebody else. This is my workaround which is not dependent on Python 2.7.x weak points:

```
- name: Download Scala package
  command: curl -o {{tempdir}}/scala.deb https://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.deb
```

Maybe this is also helpful:
I've been dealing in the past also with urllibs issue in python <2.7.9 and it helped to install this three libraries: http://stackoverflow.com/a/18579484/756056
However one of this libraries needed OS dependecies (`libffi-dev` in Ubuntu) but maybe some more advanced programmers know how to handle that only with python?!

**Comment by abadger** [comment]
@therealmarv -- note, get_url runs on the node that's being managed. So you'll need the newer python version on that node (or run get_url as a localaction and then use the copy module to push the downloaded file to the remote node).

I took a look at a similar post to that stackoverflow question.  It looked like the third-party library, requests, uses another third party library, urllib3.  urllib3 can do SNI if it has those three additional third party libraries installed.  So to get that working we'd need to add several new library dependencies.  Not good for a hard dependency but maybe okay if we only use it if the libraries are installed otherwise falling back on the stdlib-based implementation.

**Comment by therealmarv** [comment]
oh ok.

Ever thought of switching to [libcurl](http://curl.haxx.se/libcurl/python/) for that action? Curl and its proven library handles downloading with a perfect SNI support and it seems to be installed including python bindings on my barebone Ubuntu 14.04 at least:

```
vagrant@vagrant-ubuntu-trusty-32:~$ dpkg --get-selections | grep curl
curl                        install
libcurl3:i386                   install
libcurl3-gnutls:i386                install
python-pycurl                   install
python3-pycurl                  install
```

**Comment by abadger** [comment]
For the baseline modules we need to keep dependencies to the stdlib.  We can have third-party modules to do optional things so we could probably use curl here or requests or something else... But not sure that we want to standardize the extrernal library for optional things on curl... it seems like requests has won the "third-party http library" crown.  Many of the non-baseline modules already use requests.  None of them use curl.  it's just that requests has a large optional dep tree of its own for particular case :-(

**Comment by therealmarv** [comment]
I'm not against requests library, normally you can fix this by installing new packages and urllib3. But this possibilities are not there for Ansible or are IMHO too hard to get this working on a node.

I will just pin this answer here for reference about python 2.x, requests lib and SNI: https://github.com/kennethreitz/requests/issues/749#issuecomment-7442115

You should at least change the error message (and even docs) of Ansible. When I provision a server and want to download a Software package only over a HTTPS connection which is verified by a CA I would not think that Ansible has a bug with SNI.  
Many/Most Ansible user will just turn valid certificate checking off with `validate_certs=False` (because the warning message suggests that) which is much worse than using my curl workaround mentionend [above](https://github.com/ansible/ansible-modules-core/issues/1716#issuecomment-121001546)

This can be a security issue. I can only hope Ansible will use a different method than requests for this specific `get_url` action or will provide an alternative :)

**Comment by abadger** [comment]
that comment is out of date and somewhat misleading.  SNI is possible with just the stdlib in 2.7.9 and above.  SNI is possible in python2 if you use third party libraries in your code.  the question is which third party code to use.

It's a good idea about changing the warning message but the problem is it's a pretty long explanation... We can't tell the difference between SNI not being used and a server not matching its certificate at all.  So we'd have to tell people that certificate validation failed.  They could try using curl or wget via the command module if they think it's SNI related.  And they could use validate_certs if they trust the server even though the certificates mismatch.  If you have an idea about wording that's more succinct than that it would be appreciated...

**Comment by abadger** [comment]
Okay, I think that commit will fix things.  It's in the ansible/ansible repo because it's common code that's used by several modules.  It supports SNI on python-2.7.9 and above and also should mention in the error message that SNI may be one reason the code is failing.

**Comment by therealmarv** [comment]
looks really great @abadger ! I like your warning text also :+1: :)

**Comment by abadger** [comment]
Thanks for reporting this!

For those who come to this report via google, I've posted an explanation of the limitations of this fix and various workarounds here: https://github.com/ansible/ansible/issues/11579#issuecomment-121775819

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by therealmarv** [comment]
:)

**Comment by andrewrothstein** [comment]
Has anyone created a module that feels like get_url only is curl based? I've got tons of boxen/containers that are unlikely to see a python upgrade to 2.7.9+ but will need to retrieve artifacts via https.

**Comment by therealmarv** [comment]
@andrewrothstein except the warning you will get from Ansible there is nothing wrong in using this command here: https://github.com/ansible/ansible-modules-core/issues/1716#issuecomment-121001546 IMHO it is overkill to create a module for that.

**Comment by andrewrothstein** [comment]
@therealmarv get_url bakes in a chown, a chmod, and an idempotency/check for the destination file before running the download. your command does none of these.

**Comment by rasputnik** [comment]
@andrewrothstein adding a creates: {{ dest_file }} will tide me over, it'll have to do until we get a fix.

**Comment by memelet** [comment]
I _think_  from reading the above that this has been solved. But I have no idea for what version or if there some action I must take. I keep converting my `get_url`'s  to `wget` as they break.

**Comment by milo-minderbinder** [comment]
@memelet I was in the same boat as you, and was not going to let this go, so I did some digging. I'm still investigating to confirm root cause, but it looks like there was a change made to the `urllib3.contrib.pyopenssl` module in [this commit](https://github.com/shazow/urllib3/commit/1db3bba5f5bc83812810fb95803ea21971c6c052) which broke the `ansible.module_utils.urls` module's `urllib3` SNI support because the aforementioned upstream commit removed the `ssl_wrap_socket` function, which ansible's `urls` module tries to import with:

```python
try:
    try:
        from urllib3.contrib.pyopenssl import ssl_wrap_socket
    except ImportError:
        from requests.packages.urllib3.contrib.pyopenssl import ssl_wrap_socket
    HAS_URLLIB3_SNI_SUPPORT = True
except ImportError:
    HAS_URLLIB3_SNI_SUPPORT = False
```

 @abadger @bcoca  I can create a new issue if you like, or perhaps you just want to reopen this one? Not sure what the priority level is for this backwards compatibility with Python < 2.7.9, but I can try to submit a PR if the core dev team doesn't have the resources to address this any time in the near future.

**Comment by sivel** [comment]
@milo-minderbinder There is already a PR open to support newer urllib3 releases: https://github.com/ansible/ansible/pull/19962

**Comment by milo-minderbinder** [comment]
@sivel awesome! Just added a minor comment to the PR suggesting that the error message reported by Ansible is updated to report the newest workaround per [urllib3 docs](https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2). Alternatively, for people finding this issue from the Googling and hitting the SO post about `requests` [here](http://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484), _that_ workaround now just requires `idna`, `pyopenssl`, which may also be worth noting.

**Comment by xenithorb** [comment]
Interesting turn of events I just spent an hour or so on. I always test locally with vagrant any updates to the playbook before I deploy it remotely. This time `get_url` worked locally, but not remotely. So I figure, ok, it's AWS s3, maybe they're using different certs or something internal to AWS versus external. Nope, that's all good, curl, wget work. OpenSSL s_client with -severname works. 

Trolling through all the old bug reports about SNI and python2 I was left scratching my head when this was failing on Fedora 26 because that has python `2.7.13` - quite up to date.

It wasn't until I thought hmm, what do I have installed here that isn't installed elsewhere - first looking at python dependencies, `rpm -qa | grep ^python2` showed many more deps installed on the remote box. Why? Because it also had `duplicity` installed for backing up purposes, and `duplicity` requires:

* python2-urllib3 - `1.20` 
* python2-requests - `2.13.0`
* python2-pynacl - `1.1.1`
* python2-pyOpenSSL - `16.2.0`
* python2-cryptography` - `2.0.2`

as well as a few others.

I'm not exactly sure *which* one is the offending package, but I also don't think it's very good that it works better with those things uninstalled than it does with them installed. Meaning, I think the order in which it prioritizes what it's using is wrong.

When I remove `duplicity` and its dependent packages (including the above and a few others) `get_url` begins to work again, without issue.

Should this be a new bug?

**Comment by xenithorb** [comment]
Confirmed on vagrant box by itself if I add just `python2-urllib3` to the list of dependecy packages in the role (to be installed), the subsequent `get_url` fails. 

Current --requires for `python2-urllib3` is:

```
ca-certificates
python(abi) = 2.7
python-backports-ssl_match_hostname
python-cryptography
python-idna
python-ipaddress
python-pysocks
python-six
python2-pyOpenSSL
```

which pulls in:

```
Installing:
 python2-urllib3                              noarch          1.20-1.fc26               fedora           149 k
Installing dependencies:
 python-backports                             x86_64          1.0-9.fc26                fedora           9.3 k
 python-backports-ssl_match_hostname          noarch          3.5.0.1-4.fc26            fedora            17 k
 python-ipaddress                             noarch          1.0.16-4.fc26             fedora            39 k
 python2-asn1crypto                           noarch          0.22.0-4.fc26             updates          173 k
 python2-cffi                                 x86_64          1.9.1-2.fc26              fedora           223 k
 python2-cryptography                         x86_64          2.0.2-1.fc26              updates          502 k
 python2-idna                                 noarch          2.5-1.fc26                fedora            98 k
 python2-ply                                  noarch          3.9-3.fc26                fedora           107 k
 python2-pyOpenSSL                            noarch          16.2.0-6.fc26             updates           92 k
 python2-pycparser                            noarch          2.14-10.fc26              fedora           146 k
 python2-pysocks                              noarch          1.6.7-1.fc26              updates           32 k
```

**Comment by xenithorb** [comment]
Some new tickets for issue miners/googlers: 

https://github.com/ansible/ansible/issues/18528
https://github.com/ansible/ansible/issues/23642
