### ISSUE TITLE
docker env parameter changed type

### ISSUE THREAD

**Issue by hans-d** [ansible/ansible-modules-core#197]
Upgrading from 1.7.2 to 1.8 (or switching between these versions) will break playbooks/roles when using the docker module icm with the `env` parameter (it does in my case)

Compare:

https://github.com/ansible/ansible-modules-core/blob/c8e1a2077ed356fb893cd9886f758ac3d284e6b9/cloud/docker.py#L733

and 

https://github.com/ansible/ansible/blob/release1.7.2/library/cloud/docker#L684

**Comment by jimi-c** [comment]
Hi @hans-d, this was a required change to fix another issue (ansible/ansible#8199), so unfortunately the fix here will be to update your playbooks to use the dictionary syntax rather than the list syntax.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
