### ISSUE TITLE
Non-ASCII character \\xe2  in ec2_lc, line 128

### ISSUE THREAD

**Issue by fvant** [ansible/ansible-modules-core#1975]
Commit version  26 aug 18:33 

Removing that line (description) from the modules' documentation resolved the issue.

**Comment by abadger** [comment]
Thanks.  Fixed here: https://github.com/ansible/ansible-modules-core/commit/06fc029f73ccd323e355424c016bbcbbc2fb8c80

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
