### ISSUE TITLE
git module cannot clone ansible devel branch

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible-modules-core#202]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible v1.7.2, Ansible devel
##### Environment:

Ubuntu, Debian
##### Summary:

`git` module fails with an error while cloning current `devel` Ansible branch. Stable version clones correctly.
##### Steps To Reproduce:

```
ansible -i inventory localhost -m git -a 'repo=https://github.com/ansible/ansible.git dest=~/src/github.com/ansible-devel/ansible version=devel update=yes recursive=yes'
```
##### Expected Results:

```
localhost | success >> {
    "after": "d3c28fee8739c93821d4f639b2931f5a3592eb8e", 
    "before": null, 
    "changed": true
}
```
##### Actual Results:

```
localhost | FAILED >> {
    "failed": true, 
    "msg": "Failed to init/update submodules: fatal: Needed a single revision\nUnable to find current origin/master revision in submodule path 'lib/ansible/modules/core'\n"
}
```

**Comment by abadger** [comment]
This seems to be a side effect of adding the --remote flag when cloning.   Doing some forensics to figure out why we're adding that now.

**Comment by abadger** [comment]
Still thinking about how fixing this fits in with the other fixes needed for submodules.  But one note:

The ansible repository can be fixed by adding `branch=devel` to each of the ansible-modules-core and ansible-modules-extras submodules in the .gitmodules file.

**Comment by abadger** [comment]
Part one of the fix for this has now been merged: https://github.com/ansible/ansible-modules-core/pull/55

That change means that we won't try to track the HEAD of the submodules by default anymore.  So git won't be trying to pull from ansible's master branch (which doesn't exist.)

I'll be adding the branch=devel change shortly so that things will work even if someone tries:

```
ansible -i inventory localhost -m git -a 'repo=https://github.com/ansible/ansible.git dest=~/src/github.com/ansible-devel/ansible version=devel update=yes recursive=yes track_submodules=yes'
```

**Comment by abadger** [comment]
And branch=devel added here: https://github.com/ansible/ansible/commit/cb53b0f94af23599562f8375a191f45ab297e7f2

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by drybjed** [comment]
@abadger Thanks for your work! :-) Now waiting for the `with_items` fix in devel...
