### ISSUE TITLE
docker_url unix:/// vs unix://

### ISSUE THREAD

**Issue by a-sk** [ansible/ansible-modules-core#221]
**Issue Type:**
Bug Report

**Ansible Version:**
ansible 1.7.2

**Environment:**
Mac OS X 10.10

**Summary:**
Docker module doesn't allow to use usual schema `unix:///`, only `unix://` works.

`unix:///path/to/socket` gets converted to `unix:/path/to/socket` and docker-py doesn't understand this path.

**Steps To Reproduce:**
set `docker_url` as `unix:///path/to/socket` in docker task

**Expected Results:**
docker module should be able to correctly parse docker url and connect to docker server

**Actual Results:**
Exceptions is raised:

``` python
docker.errors.DockerException: ('Invalid port: %s', 'unix:/path/to/socket')
```

**Comment by abadger** [comment]
This was fixed as a side effect of d046425049c9b644458592011f3c22b338eea88a

The problem that python's urlparse method  was being run on the provided docker-url to normalize it.  Unfortunately, docker itself doesn't understand the normalized url as you noted and therefore it returned the error.  The new code simply passes the url through unchanged.

That code shouold be i nthe current 1.9.x releases.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
