### ISSUE TITLE
ec2_asg crashes when ELB has no instances , KeyError: 'instance_facts'

### ISSUE THREAD

**Issue by fvant** [ansible/ansible-modules-core#2233]
When I create an ASG, and subsequently wait for instances to become healthy, this block gives an exception.
Looking in the code ec2_asg.py, instance_facts only gets set when it has instances.

``` yaml
- name: wait for viable_instances >= desired
  ec2_asg:
    name: "{{'asg-'+service.servicename+'-'+resource_env|default(env)+'-'+timestamp}}"
    region: "{{aws.region}}"
    health_check_type: "{{health_check_type}}"
    health_check_period: 60
  register: this_asg
  until: this_asg.viable_instances >= {{service.desired}}
  retries: 15
```

``` yaml
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/fvant/.ansible/tmp/ansible-tmp-1444381237.37-276495144647502/ec2_asg", line 2863, in <module>
    main()
  File "/home/fvant/.ansible/tmp/ansible-tmp-1444381237.37-276495144647502/ec2_asg", line 2852, in main
    create_changed, asg_properties=create_autoscaling_group(connection, module)
  File "/home/fvant/.ansible/tmp/ansible-tmp-1444381237.37-276495144647502/ec2_asg", line 2536, in create_autoscaling_group
    wait_for_elb(connection, module, group_name)
  File "/home/fvant/.ansible/tmp/ansible-tmp-1444381237.37-276495144647502/ec2_asg", line 2398, in wait_for_elb
    healthy_instances = elb_healthy(asg_connection, elb_connection, module, group_name)
  File "/home/fvant/.ansible/tmp/ansible-tmp-1444381237.37-276495144647502/ec2_asg", line 2362, in elb_healthy
    for instance, settings in props['instance_facts'].items():
KeyError: 'instance_facts'
```

**Comment by bcoca** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
