### ISSUE TITLE
creates option in services module

### ISSUE THREAD

**Issue by TaiSHiNet** [ansible/ansible-modules-core#2271]
As some custom startup options create initial folders/etc.
Depends on #2266

**Comment by chrrrles** [comment]
Hello TaiSHiNet - can you provide some more information on this feature request?

**Comment by TaiSHiNet** [comment]
@chrrrles It would be great for something similar to 'creates' option in 'command' module.
i.e. I currently have this:

```
- name: initialize zookeeper service
  command: service zookeeper-server init creates=/var/lib/zookeeper
```

Which indeed initializes Zookeeper's environment, specifically creating /var/lib/zookeeper folder/etc

**Comment by kustodian** [comment]
I don't see a reason for this, when you can just use the command module like in your example? There would be no benefit from this, especially since different services have different init commands, e.g. `zookeeper-server` has `init`, `postgres` has `initdb`, etc, so the `service` module itself would need support a custom `state` value.

**Comment by bcoca** [comment]
closing for the same reasons as mentioned in #2266
