### ISSUE TITLE
Add 'eu-central-1' to AWS_REGIONS in ec2 module

### ISSUE THREAD

**Issue by adonig** [ansible/ansible-modules-core#229]
##### Issue Type:

“Bug Report”
##### Ansible Version:

ansible 1.7.2
##### Environment:

“N/A”
##### Summary:

Ansible misses support for the new AWS Frankfurt region. You can fix it by adding 'eu-central-1' to AWS_REGIONS in lib/ansible/module_utils/ec2.py
##### Steps To Reproduce:

Try to create a stack in region 'eu-central-1' with the cloudformation module.
##### Expected Results:

It should create the stack.
##### Actual Results:

It fails with the following error message:

```
msg: value of region must be one of: ap-northeast-1,ap-southeast-1,ap-southeast-2,eu-west-1,sa-east-1,us-east-1,us-west-1,us-west-2, got: eu-central-1
```

**Comment by adonig** [comment]
Original issue was: https://github.com/ansible/ansible/issues/9414

Another user called cchurch asked there, if it would "make more sense to use boto.regioninfo.get_regions("service_name") instead of maintaining a separate list of regions".

**Comment by jimi-c** [comment]
Hi @adonig, sorry for bouncing you here, but there is a PR already opened to address this on the main repo too (https://github.com/ansible/ansible/pull/9419), so we're going to go ahead and close this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
