### ISSUE TITLE
Docker pull failing with Docker 1.8.3 and legacy docker registries.  

### ISSUE THREAD

**Issue by ryanwalls** [ansible/ansible-modules-core#2351]
Docker: 1.8.3
Ansible: 1.9.4-1
Docker-py: 1.5.0

When trying to pull images from a legacy docker registry (quay.io), I get this error:

```
Status: Image is up to date for quay.io/mycompany/jenkins:latest\"}\r\n", "{\"status\":\"quay.io/3dsim/jenkins: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.\"}\r\n"], "failed": true, "status": "quay.io/mycompany/jenkins: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker."}
msg: Unrecognized status from pull.
```

**Comment by daviddyball** [comment]
I'm seeing this when using images uploaded to the official Docker Hub, but only for really old images that haven't been updated in quite some time. The fix for me was to pull the images in question with `1.8.3` and re-push them back up to the registry. This ensures the images are put into the `/v2/` registry endpoint instead of remaining in the old `/v1/` endpoint.

TBH I'm not sure if Ansible should be working around this issue though. It is a legacy registry issue, not really a docker or Ansible issue. I totally understand that it's a pain in the backside though, especially if you use a 3rd-party registry to host your Docker images (like quay.io or ECR).

The other option to workaround this is to pin docker at `1.8.2` for the time being.

**Comment by ryanwalls** [comment]
Thanks @daviddyball.  Yeah, I worked around it for now by using Docker Hub instead of Quay.io.  

As far as the fix, I guess my thinking is that it shouldn't treat the warning as an error.  But probably a low priority problem.

**Comment by mtpereira** [comment]
I've also hit on this while using tutum.co private registry. I think I've fixed this, I'll PR it.

**Comment by robynbergeron** [comment]
@ryanwalls -- thanks for submitting this bug report. 

@softzilla --  thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by robynbergeron** [comment]
[module: cloud/docker/docker_image.py]

**Comment by robynbergeron** [comment]
@mtpereira -- also, thanks for the PR on this :)

**Comment by mohan08p** [comment]
same issue with rancher os. But, yes with the above things by @daviddyball , it can be resolved upto the mark. Thanks.
