### ISSUE TITLE
ec2_remote_facts throws unsupported parameter for module: aws_secret_key

### ISSUE THREAD

**Issue by chachra** [ansible/ansible-modules-core#2361]
Took from http://docs.ansible.com/ansible/ec2_remote_facts_module.html ?
-   name: Find EC2 instances
  ec2_remote_facts:
      key: Name
      value: "{{ aws_project_name_env_branch }}"
      region: "{{ aws_region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
  register: ec2_instances

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: aws_secret_key"}

**Comment by robynbergeron** [comment]
Hi @chachra:

The ec2_remote_facts module is an extras module -- please file your issue here: https://github.com/ansible/ansible-modules-extras

You might want to consider giving us the following additional information to help the module maintainer identify the issue: https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md

Thanks!
