### ISSUE TITLE
win_get_url doesn't properly download files invoked with javascript

### ISSUE THREAD

**Issue by christonog** [ansible/ansible-modules-core#2369]
While attempting to download an .msi for the PCXS powershell module (dependency of win_unzip).

On line 61 of win_get_url.py, $client.DownloadFile($url, $dest) is used. Perhaps, for files that are downloaded without a file extension (.msi, .jpg, etc) using invoke-webrequest would be best. It's slower, so it should only be used for these types of downloads.

```
$url = "https://pscx.codeplex.com/downloads/get/923562"
$dest = "C:\Users\Administrator\Downloads"

$client.DownloadFile($url, $dest) # only downloads the webpage

invoke-webrequest -uri $url -outfile $dest #downloads the msi
```

**Comment by robynbergeron** [comment]
[module: windows/win_get_url.py]

**Comment by robynbergeron** [comment]
@christonog Thanks for submitting this feature idea.

@angstwad --  Pinging you to bring this feature request to your attention. Please note that you are under no particular obligation to add this feature.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. Consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

**Comment by nitzmahone** [comment]
Thanks for the info- the specific URL you gave helps me understand the issue clearly. Unfortunately, Invoke-WebRequest places the entire file in memory, and has various other issues that might cause us grief. I'd be hesitant to apply any kind of heuristic to automatically using it (eg, extensionless URL) as that would likely break as many things as it fixes. In the case of codeplex downloads, you can get the full URL from F12/dev tools (for the URL above, http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=pscx&DownloadId=923562&FileTime=130585918034470000&Build=21031). 

We probably won't be implementing this request as-is, due to the issues I've mentioned. I'd definitely consider a pull request that has an explicit switch to use Invoke-WebRequest, though...

Thanks!
