### ISSUE TITLE
It seems that the win_fetch module is missing.

### ISSUE THREAD

**Issue by ypid** [ansible/ansible-modules-core#2407]
##### Issue Type:

Feature Idea
##### Ansible Version:

Ansible 2.0 devel
##### Ansible Configuration:

Default.
##### Environment:

Debian Jessie
##### Summary:

It seems that the win_fetch module is missing. https://github.com/ansible/ansible-modules-core/tree/devel/windows

**Comment by jhawkesworth** [comment]
No need, you can use fetch even on windows like this:

  fetch: "src=C:/SomeFoldere/some-interesting-file dest=/tmp/fetched/{{ inventory_hostname_short }}/ flat=yes"

**Comment by ypid** [comment]
Interesting. I was just confused because there is a [win_copy](https://github.com/ansible/ansible-modules-core/blob/devel/windows/win_copy.py) module but no win_fetch. Is there a reason why for one direction there is a special windows module and for the other direction the default module is used?

**Comment by ypid** [comment]
@nitzmahone Can you answer my question from my last comment?

**Comment by nitzmahone** [comment]
@ypid It's mostly because the necessary functionality is completely implemented by the winrm connection plugin. Connection plugins have a set of required actions necessary for Ansible to "do its thing" on a given platform (eg, make tempdir, delete tempdir, put file, get file, execute command). The default fetch action that runs on the controller side (fetch isn't actually a module) just asks the connection plugin to "go get me this file", and it works unmodified on the winrm connection plugin. copy, OTOH, has Windows-specific args and behavior that aren't completely implemented by the connection plugin, so it needed its own module. We've kicked around aliasing win_X for the builtin actions that "just work" unmodified, but it hasn't happened thus far.

**Comment by ScriptMyJob** [comment]
I have attempted to use the fetch module on Windows Server 2016 but end up with the following:

```
root@ip-10-31-6-80:~/Project/Ansible# ansible server4 -i inventory -m fetch -a "src=C:\Users\user\Desktop\Release.2017.07.0.226.zip dest=/root/Release.2017.07.0.226.zip validate_checksum=no" -vvvvv
ansible 2.4.1.0
  config file = /root/Project/Ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Using /root/Project/Ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /root/Project/Ansible/inventory inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/windows/win_stat.ps1
<server4> ESTABLISH WINRM CONNECTION FOR USER: ansible_user on PORT 5986 TO server4
<server4> WINRM CONNECT: transport=ssl endpoint=https://server4:5986/wsman
<server4> WINRM OPEN SHELL: D11C84F2-0764-421D-B5DC-B95EBBB601B9
EXEC (via pipeline wrapper)
<server4> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-']
<server4> WINRM RESULT u'<Response code 0, out "{"changed":false,"ms", err "An error occurred wh">'
<server4> WINRM CLOSE SHELL: D11C84F2-0764-421D-B5DC-B95EBBB601B9
server4 | SUCCESS => {
    "changed": false, 
    "failed": false, 
    "file": "C:\\Users\user\\Desktop\\Release.2017.07.0.226.zip", 
    "msg": "unable to calculate the checksum of the remote file, not transferring, ignored"
}
META: ran handlers
META: ran handlers
root@ip-10-31-6-80:~/Project/Ansible# 
```

Any suggestions on how I can get around this?

**Comment by jhawkesworth** [comment]
@ScriptMyJob - please open a new issue rather than commenting on a closed issue.  I only happened to see this by chance, typically closed bugs are not monitored.

Is your .zip file still being written to?  Is there a file handle still open to it?  check with resource monitor -> cpu -> search for file handles
How big is the file?.
Also dest needs to be a dir, not a file, and you may want to use 'flat: yes' if you are only fetching from a single host.
