### ISSUE TITLE
apt: deb="file.deb" always changed

### ISSUE THREAD

**Issue by drzraf** [ansible/ansible-modules-core#2430]
using ansible 1.9.4

**Comment by robynbergeron** [comment]
[module: packaging/os/apt.py]

**Comment by robynbergeron** [comment]
@drzraf Thanks for submitting this bug report. You might want to consider giving us the following additional information to help the module maintainer identify the issue: https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md

@mgwilliams thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by Jmainguy** [comment]
This is because of 

pkg = apt.debfile.DebPackage(deb_file)

apt.debfile.DebPackage is useless, compare_to_version_in_cache does not work, and it provides no classes to return a version number, or even the package name. Going to work on getting name and version from dpkg and then checking version with apt_pkg

**Comment by Jmainguy** [comment]
@mgwilliams @drzraf Give #2675 a shot. Works for me on Debian 8.

**Comment by drzraf** [comment]
tested, works well. thanks!
(although it could internally be made a bit more elegant, see comments for the PR)
