### ISSUE TITLE
new state "check" in module lineinfile

### ISSUE THREAD

**Issue by guard43ru** [ansible/ansible-modules-core#2497]
At now use this construction:

```
- name: Check whether /tmp/my.conf contains "127.0.0.1"
  command: awk /^127.0.0.1$/ /tmp/my.conf
  register: checkmyconf
  changed_when: False

- name: Greet the world if /tmp/my.conf contains "127.0.0.1"
  debug: msg="Hello, world!"
  when: checkmyconf.stdout | match("127.0.0.1")
```

It is good idea add state=check:

```
- name Check whether /tmp/my.conf contains "127.0.0.1"
  lineinfile: state=check regexp="127.0.0.1"
```

discussion here: http://stackoverflow.com/questions/30786263/only-check-whether-a-line-present-in-a-file-ansible

**Comment by bcoca** [comment]
find module has contains option that can already be used for this purpose, in any case running in -check mode should tell you if the line is matched and needs updating

**Comment by tembaby** [comment]
Totally agree with original requester, having this feature in "lineinfile.py" is logical, find is not supported in prior to v2.0, running in check mode is not always helpful since usually I need this feature in a non-check ansible mode.  I have made this modification against the current development version of lineinfile.py, i tested it and I hope it get accepted.

[lineinfile.py.zip](https://github.com/ansible/ansible-modules-core/files/60295/lineinfile.py.zip)
