### ISSUE TITLE
apt default-release faling with lists

### ISSUE THREAD

**Issue by moozer** [ansible/ansible-modules-core#2506]
When I do

>    apt: name={{ item }} state=present default-release=testing
>    with_items:
> - nodejs
> - mongodb
> - npm

I get an error saying

> SystemError: E:The value 'xxx' is invalid for APT::Default-Release as such a release is not available in the sources

But when I do

>    apt: name=nodejs state=present default-release=testing

It works. 

It seems to be a bug.
Can I supply any more relevant info?
## 

Versions
$ ansible --version
ansible 1.9.2

And the target machine (new debian jessie)
$ uname -a
Linux vagrant 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

**Comment by jimi-c** [comment]
This is most likely due to the fact that the apt (and other packaging modules) squash the items list down to a single execution to save time/speed things up. One of the other packages in this list must not be valid with the `default-release=testing` param.

As this does not appear to be a bug in the way Ansible is working, I am going to go ahead and close this now. If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
