### ISSUE TITLE
BUG win_unzip: force to declare properties on v2.0.0-0.6.rc1

### ISSUE THREAD

**Issue by juju4** [ansible/ansible-modules-core#2572]
Hello,

When using win_unzip, ansible force me to declare (false or true) properties creates, recurse, rm. no default value, it seems.

ex:

```
- name:  unzip
  win_unzip:
      src: "{{ bin_path }}\\master.zip"
      dest: "{{ bin_path }}"
#      creates: false
#      recurse: false
#      rm: false
```

which results in

```
TASK [xxx :  unzip] *****************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: +     ~~~~~~~~~~~~~~~
fatal: [192.168.2.109]: FAILED! => {"changed": false, "failed": true, "msg": "La propri?t? ??creates?? est introuvable dans cet objet. V?rifiez qu?elle existe."}
```

with the 3 properties, it works good
Message is french and means: properties creates was not found in this object. Verify it exists.

Note: seems to also have issue with accent support.
windows guest (virtualbox) is French while host linux lubuntu trusty is fr UTF8

```
C:\Users\user>reg query "hklm\system\controlset001\control\nls\language" /v Installlanguage

HKEY_LOCAL_MACHINE\system\controlset001\control\nls\language
    Installlanguage    REG_SZ    040C
```

**Comment by robynbergeron** [comment]
Hi @juju4 --

The win_unzip module is actually an extras module -- can you open the issue there instead, so that it can get routed properly? 

Thanks!

(https://github.com/ansible/ansible-modules-extras/issues/new is the place :D)

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!
