### ISSUE TITLE
ec2_ami doesn't handle other errors

### ISSUE THREAD

**Issue by Java1Guy** [ansible/ansible-modules-core#2631]
When encountering an error, it assumes it is a timeout issue.  The current version put out a message:
"Error while trying to find the new image. Using wait=yes and/or a longer wait_timeout may help."

Increasing the timeout had no effect.  When I included the error code in the message on line 178:
module.fail_json(msg="Error "+e.error_code+" while trying to find the new image. Using wait=yes and/or a longer wait_timeout may help.")

It said:
"Error 'UnauthorizedOperation' while trying to find the new image. Using wait=yes and/or a longer wait_timeout may help."

**Comment by jjshoe** [comment]
@Java1Guy - The latest version now includes the error message:

https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2_ami.py#L400

**Comment by jctanner** [comment]
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
