### ISSUE TITLE
user_data parameter for digital_ocean

### ISSUE THREAD

**Issue by lcacciagioni** [ansible/ansible-modules-core#2634]
Seems to be that the paramater `user_data` on the `digital_ocean` is not supported, I'm using the following versions:

```
ansible==1.9.4
dopy==0.3.7
ecdsa==0.13
Jinja2==2.8
MarkupSafe==0.23
paramiko==1.16.0
pycrypto==2.6.1
PyYAML==3.11
requests==2.8.1
six==1.10.0
```

but when I try to use the parameter `user_data` for digital ocean it continues to say that this paramter is not supported, is there any reason? And if this is really not supported why it is still available in the official docs?

Thanks,
Leandro.-

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

It appears this feature was merged in with Ansible 2.0, so I have updated the version_added field to reflect this. This will be visible the next time we build/push docs.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
