### ISSUE TITLE
Synchronize fails when target host key changed

### ISSUE THREAD

**Issue by danielsiwiec** [ansible/ansible-modules-core#270]
##### Issue Type:

Bugfix Pull Request
##### Ansible Version:

1.7.2
##### Environment:

N/A
##### Summary:

Related to #9442 in ansible/ansible.
When skipping "Host Key Checking" two flags need to be passed to ssh in order to allow connection to a host with a changed host key: StrictHostKeyChecking=no and UserKnownHostsFile=/dev/null. Currently only the first one is passed.
##### Steps To Reproduce:
1. export ANSIBLE_HOST_KEY_CHECKING=False
2. ansible all -m synchronize -a "src=. dest=~/" -i "hostname.example.com," -vvvv
3. Change the host key (recreate the VM or copy the known_host entry for a different host) for the target
4. ansible all -m synchronize -a "src=. dest=~/" -i "hostname.example.com," -vvvv
##### Expected Results:

The synchronize should pass.
##### Actual Results:

```
dans-ssh-test.cloudapp.net | FAILED >> {
    "cmd": "rsync --delay-updates -FF --compress --archive --rsh 'ssh  -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \".\" \"halo-ci-user@dans-ssh-test.cloudapp.net:~/\"",
    "failed": true,
    "msg": "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nThe RSA host key for dans-ssh-test.cloudapp.net has changed,\r\nand the key for the corresponding IP address 191.239.37.222\r\nis unknown. This could either mean that\r\nDNS SPOOFING is happening or the IP address for the host\r\nand its host key have changed at the same time.\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nIT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!\r\nSomeone could be eavesdropping on you right now (man-in-the-middle attack)!\r\nIt is also possible that a host key has just been changed.\r\nThe fingerprint for the RSA key sent by the remote host is\nbf:ee:23:b9:43:d2:18:74:d5:2f:68:4c:7d:33:29:67.\r\nPlease contact your system administrator.\r\nAdd correct host key in /Users/dsiwiec/.ssh/known_hosts to get rid of this message.\r\nOffending RSA key in /Users/dsiwiec/.ssh/known_hosts:64\r\nPassword authentication is disabled to avoid man-in-the-middle attacks.\r\nKeyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at /SourceCache/rsync/rsync-42/rsync/io.c(452) [sender=2.6.9]\n",
    "rc": 255
}
```

**Comment by leocrawford** [comment]
Is there a plan to merge this back in? Is there a workaround?

**Comment by danielsiwiec** [comment]
@bcoca Looks like people are still having problems with this. Also see ansible/ansible#9442

**Comment by verdurin** [comment]
Yes, I'm seeing this with 2.0.0.2.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- "ANSIBLE_HOST_KEY_CHECKING=False" should also append "UserKnownHostsFile=/dev/null" to the rsync ssh args.

However, however what is happening is that:
- ANSIBLE_HOST_KEY_CHECKING does not affect the ssh arguments passed to rsync by the synchronize module. In Ansible 2.x the parameter "verify_host" was added to the module as the primary way to turn on/off stricthostkeychecking. The default is "no", so stricthostkeychecking is set to false by default unless the user overrides it. In my testing with 2.x, stricthostkeychecking=no is sufficient to cause rsync to ignore the fingerprint error. The error still appears in the rsync stderr which is not captured by the module's return json. Although the error appears, it does not prevent rsync from functioning and the returncode is zero.

We would suggest:
- Update to a newer version of ansible and use the verify_host parameter to control synchronize's hostkeychecking instead of setting ANSIBLE_HOST_KEY_CHECKING.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
