### ISSUE TITLE
cron module: add jobs into /etc/crontab, not /etc/cron.d/...

### ISSUE THREAD

**Issue by tyleha** [ansible/ansible-modules-core#2763]
**Issue Type:**

Feature Pull Request

I'll be submitting a PR for this shortly, be on the lookout.

**Ansible Version:**

```
ansible 2.1.0 (devel 095790ac5c) last updated 2016/01/05 15:15:08 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 33014c6db1) last updated 2016/01/05 15:43:25 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 82a4cf84be) last updated 2016/01/05 15:43:33 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Environment:**
Ubuntu 14.04.3

**Summary:**

Reopening an incorrectly closed issue from https://github.com/ansible/ansible/issues/4881.

Unfortunately commit [4384114ed6fc901e1503310f23aac4e5589bf283](https://github.com/ansible/ansible/commit/4384114ed6fc901e1503310f23aac4e5589bf283) only allows you to specify a relative path to a cron file within `/etc/cron.d`. This did not address the initial concern in [#4481](https://github.com/ansible/ansible/issues/4881) which looked to add cron entries to `/etc/crontab`. As mentioned in that issue, not all distros of cron support the `cron.d/` folder like BusyBox which runs on Raspberry Pi and Synology hardware.

**Expected Results:**

When passing the `cron_file` field my crontab file at `/etc/crontab`, I expect crontab to be updated.

**Actual Results:**

IOError: [Errno 2] No such file or directory: '/etc/cron.d//etc/crontab'\r\n"

Running a `cron` command without specifying `cron_file` gives

```
{"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1452034919.04-75440676654700/cron\", line 2504, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1452034919.04-75440676654700/cron\", line 454, in main\r\n    crontab = CronTab(module, user, cron_file)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1452034919.04-75440676654700/cron\", line 188, in __init__\r\n    self.read()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1452034919.04-75440676654700/cron\", line 209, in read\r\n    raise CronTabError(\"Unable to read crontab\")\r\n__main__.CronTabError: Unable to read crontab\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by tyleha** [comment]
#2768 is a simple and good solution to this.

**Comment by jimi-c** [comment]
Hi @tylerhartley, it appears the above was merged, so closing this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
