### ISSUE TITLE
Invalid -N option for useradd on RedHat 5.

### ISSUE THREAD

**Issue by ienliven** [ansible/ansible-modules-core#277]
Hello guys, 

I found a issue on user module running on RedHat 5, it seems useradd has no -N option, which is appended when group already exists. 

TASK: [common | user name=development password={{ development_password_crypt }} groups=development shell=/bin/bash appen
d=yes] ***
failed: [54.172.129.218] => {"failed": true, "name": "development", "rc": 2}
msg: /usr/sbin/useradd: invalid option -- N
Usage: useradd [options] LOGIN
...

[root@ip-172-31-223-71 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 5.8 (Tikanga)

[root@ip-172-31-223-71 ~]# uname -a
Linux ip-172-31-223-71 2.6.18-308.24.1.el5xen #1 SMP Wed Nov 21 11:45:43 EST 2012 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@ip-172-31-229-206:~/ansible$ git status
On branch devel
Your branch is up-to-date with 'origin/devel'.

modules/core/system/user.py:
        elif self.group_exists(self.name):
            # use the -N option (no user group) if a group already
            # exists with the same name as the user to prevent
            # errors from useradd trying to create a group when
            # USERGROUPS_ENAB is set in /etc/login.defs.
            cmd.append('-N')

Ping me if need more info.

**Comment by Jmainguy** [comment]
@ienliven @bcoca https://github.com/ansible/ansible-modules-core/pull/342 has been created to address this.

I tested the fix against 
centos5
centos6
centos7
opensuse 13.1
ubuntu 14.10
ubuntu 14.04
arch 

using the following playbook.

```
---

- name: Ensure user is not present
  user: name=ienliven state=absent

- name: Add user
  user: name=ienliven state=present

- name: Remove user again
  user: name=ienliven state=absent

- name: Add back just the group
  group: name=ienliven state=present

- name: Add user to group that already exists
  user: name=ienliven state=present
```

**Comment by abadger** [comment]
Merged @Jmainguy's PR: https://github.com/ansible/ansible-modules-core/pull/342

That should fix the issue reported here.  Thanks guys, fo the bug report and the fix!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
