### ISSUE TITLE
docker module: pull all version of images if version is null

### ISSUE THREAD

**Issue by awasilyev** [ansible/ansible-modules-core#2851]
In case of mistakenly specify 'null' as image version for docker module it tries to pull all versions of this image, wasting disk space. Reproduced both in 1.9.4 and 2.0

Steps to reproduce:
docker 1.9.1
ansible -m docker -a 'state=reloaded name=test net=bridge image=centos:' -c local localhost

Actual result:
docker tries to pull all existing centos image version

Expected result:
pulling only centos:latest or failing with 'image not found' error

**Comment by awasilyev** [comment]
mistakenly closed by github

**Comment by jimi-c** [comment]
Merged and cherry-picked to `stable-2.0`. Thanks!

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
