### ISSUE TITLE
S3 static website support

### ISSUE THREAD

**Issue by gdamjan** [ansible/ansible-modules-core#2859]
Issue Type:   Feature Idea
Ansible Version: 2.0.0.2
Ansible Configuration: none
Environment: Arch, Debian
Summary:
AWS S3 can be used to host a static website. The AWS Console has the option to enable it, also to set the index page and the error (404) page. In Boto the method on a bucket is `configure_website`.

http://docs.pythonboto.org/en/latest/ref/s3.html?highlight=configure_website#boto.s3.bucket.Bucket.configure_website

Steps To Reproduce:
Expected Results:
Actual Results:

**Comment by wimnat** [comment]
PR for this has been open for a while... https://github.com/ansible/ansible-modules-extras/pull/662

Test it out and give it the thumbs up and maybe we can get it merged.

There's also a PR for s3 website redirect rules https://github.com/ansible/ansible-modules-extras/pull/663

**Comment by jimi-c** [comment]
As there's already an outstanding PR for this, I'll go ahead and close this issue.

If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
