### ISSUE TITLE
cron module does not correctly use sudo

### ISSUE THREAD

**Issue by phiroict** [ansible/ansible-modules-core#2882]
Ansible : 1.9.2
OS : Ubuntu 14.04.3 (vagrant / virtualbox) 

With the task:

```

---
  - name: Install crontab for restarting mule
    sudo: yes
    cron:
      state=present
      name="Restart mule node"
      user=root
      hour=8
      minute=0
      day=1
      month="{{ cron }}"
      job="/sbin/service {{ servicename }}"
```

And host: 

```
192.168.50.2 ansible_ssh_user=somename ansible_sudo_user=somenametoo servicename=dummy cron="3,6,9,12"
```

Calling the playbook: 

```
ansible-playbook --ask-pass --ask-sudo-pass -i roles/host install-crontab-uat.yml
```

EXPECTING: 
crontab entry created for the root user 

I GOT: 

```
TASK: [crontab-restartmule-cluster-rolling | Install crontab for restarting mule] ***
failed: [192.168.50.2] => {"failed": true}
msg: must be privileged to use -u
```

Double checked the password and the sudo-password.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Your issue is not a bug, "somenametoo" must be a privileged user to use `crontab -u`, which normally means root.  If you avoid setting  `ansible_sudo_user` that will be the default.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
