### ISSUE TITLE
Docker Module - Container networking

### ISSUE THREAD

**Issue by RafPe** [ansible/ansible-modules-core#2892]
Hey , 

Since latest release of Docker we have option to use own bridge networks and as well for clustering we can use overlay networks. If I'm correct this is not available at the moment in docker module ? 
If thats the case is there plan to add it ?

**Comment by jimi-c** [comment]
Hi @RafPe, we are looking at improving the docker module support in the near future, so for now I'm going to close this issue. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
