### ISSUE TITLE
os_server feature regression.

### ISSUE THREAD

**Issue by mcameron** [ansible/ansible-modules-core#2920]
**Issue Type:**

Regression

**Ansible Version:**
2.0.0.2

**Ansible Configuration:**

N/A

**Environment:**

OSX El Capitan

**Module:**

os_server

**Summary:**

"unsupported parameter for module: user_data"

**Steps To Reproduce:**

Port a playbook from the "deprecated" nova_compute module to the os_server module.  

**Expected Results:**

user_data parameter continues to be supported.

**Actual Results:**

user_data parameter is not supported.

**Comment by jimi-c** [comment]
cc @emonty @Shrews

**Comment by emonty** [comment]
Hi! The parameter in os_server is called 'userdata'. We can surely add an alias to user_data - but until that lands, userdata should do the trick for you.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
