### ISSUE TITLE
Prescribed method to disassociate EIP without previous knowledge of association?

### ISSUE THREAD

**Issue by shaunbrady** [ansible/ansible-modules-core#2950]
Hello,
    Previously I had a playbook that would create an instance and associate an EIP with it.  If this EIP was on another host, it would just be moved.  I now get:

```
<Response><Errors><Error><Code>Resource.AlreadyAssociated</Code><Message>resource eipalloc-d26705b6 is already associated with associate-id eipassoc-f7bf1d8f</Message></Error></Errors><RequestID>693c1800-0a6d-4af4-9587-3f715fd8bd8c</RequestID></Response>
```

I believe the change is moving from EC2-Classic to VPC.  If I just try use ec2_eip to disassociate the address, I need to provide the instance id it is currently associated with.  I don't see a straight forward way to look up this instance, as 1) I'm already in a play connected to a host, but more importantly 2) I don't know if the host is up.

Is there a method I'm missing to say "disassociate this regardless of its current status", or to easily look up the instance associated with the EIP?

For reference we are still on 1.9, but if the answer is in 2.0, that is in our future.

Thanks!

**Comment by jimi-c** [comment]
Hi @shaunbrady, this is more of a general use question, and we reserve Github issues/PRs for bugs and feature requests. It would be best if you asked your question on one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
