### ISSUE TITLE
[Bug report] Deprecation warning despite no precense of issues warned about

### ISSUE THREAD

**Issue by wfaler** [ansible/ansible-modules-core#3021]
I receive the following deprecation warning:

```
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default)....
```

I have done a thorough search and replace through the project, and find no uses of `sudo` or `sudo_user`. All instances of `sudo` have been replaced with `become`.

Would Ansible warn about plugins used that still use sudo/sudo_user? If so, this can be closed, otherwise, this is likely a bug.

Ansible Version: 2.0.0.2
Ansible cfg: clean from install
Environment: OS X 10.11, controlling Ubuntu 14.04.1

**Comment by nitzmahone** [comment]
I'm pretty sure it's not possible for this warning to be generated erroneously (and it can't be generated by plugins- only core objects that inherit from Become). Is it possible you're using a sneaky galaxy role or something that's got the sudo in it? 

We do actually know the file and line number that the offending task is in when the warning is generated, but because we collapse multiple instances of the deprecation warnings down (on purpose), we can't just append the line number to the message without breaking that feature. Perhaps we could add an optional position to Display.deprecated(), then add to the debug output or allow the positions to be shown via config...

**Comment by wfaler** [comment]
It will be an Ansible Galax role. However, it would be nice to know what the offending code is.

I'll let you judge whether you want to close this altogether, or keep it open as a feature idea.

**Comment by jctanner** [comment]
@wfaler please file this in https://github.com/ansible/ansible/issues
