### ISSUE TITLE
ec2_tag.py - fails with AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible-modules-core#3057]
##### Issue Type:

Bug Report
##### Ansible Version:

2.1.0-0.git201602171412.91f3558.devel.el7.centos
##### Ansible Configuration:

Defaut.
##### Environment:

CentOS Linux release 7.2.1511 (Core)
##### Summary:

After upgrading Ansible from the latest devel branch (91f3558c) the ec2_tag.py module stopped working properly when state: present.
##### Steps To Reproduce:

```
- name: Tag instance
  ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ id }}"
    state: present
    tags:
      Name: Web
```
##### Expected Results:

Instance to be tagged.
##### Actual Results:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/endavaMgmt/.ansible/tmp/ansible-tmp-1455744343.09-48096359565613/ec2_tag", line 2472, in <module>
    main()
  File "/home/endavaMgmt/.ansible/tmp/ansible-tmp-1455744343.09-48096359565613/ec2_tag", line 152, in main
    if set(tags.items()).issubset(set(tagdict.items())):
AttributeError: 'str' object has no attribute 'items'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "ec2_tag"}, "parsed": false}
```

**Comment by Constantin07** [comment]
Update - fixed in PR #3058

**Comment by Grindizer** [comment]
Hi everyone, 
The same problem happen with cloudformation module when we use the "tags" parameter, 
could we include the fix there as well, or shall we open another bug/PR ?
(or also check in all modules that use "tags" parameter ?)

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

The above commit was merged in, and should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by Constantin07** [comment]
@Grindizer this has been fixed in cloudformation now.

**Comment by Grindizer** [comment]
\o/ great !
