### ISSUE TITLE
Disabling a service that does not exist (EL 5.x and 6.x) - ansible v2

### ISSUE THREAD

**Issue by tarunyx** [ansible/ansible-modules-core#3059]
When trying to disable a service that does not exist (e.g. because the dependent package has been removed) on EL 5.x and 6.x, ansible fails and stops processing tasks giving the following error:

"no service or tool found for: SERVICE_NAME"

Examining the code shows that this is expected due to the fact '/etc/init.d/SERVICE_NAME' is missing, thus causing ansible to think that an error occured since 'self.enable_cmd' isn't assigned to anything. That being said, wouldn't it make sense to flag the task as skipped instead of throwing an error and exiting?

Currently, the only workaround I can imagine is adding 'ignore_errors: yes' on the affected tasks. For what is worth, systems using systemctl seem to be unaffected.

**Comment by jimi-c** [comment]
Hi @michailsideris-gvf, the issue here is, how is Ansible supposed to know? It has traditionally been an error to use the service module on a non-existent service, so changing that now would have too many ramifications. As you noted, specifying `ignore_errors: yes` here would be the best option, however I fail to see what use it does to disable a service after removing the package.

As this is more of a general use question, I'm going to go ahead and close this issue. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
