### ISSUE TITLE
git force should default to no

### ISSUE THREAD

**Issue by jareddlc** [ansible/ansible-modules-core#306]
Please consider changing the git clone force to default to no, as I've just lost a days worth of work.

**Comment by abadger** [comment]
The behaviour of force was the default before force was added so unfortunately it's about backwards compatibility.  I do understand your concern with its behaviour, though.  Perhaps take this up on the devel mailing list to see if a consensus can be reached to break compatibility in favor of having a safer default.

**Comment by abadger** [comment]
We've decided to take a look at all the modules and change defaults to false as a safety feature for an upcoming release.  So I will hopefully be switching the defaults on this shortly.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
