### ISSUE TITLE
command and shell modules returning "unsupported parameter" for parameter in the target command

### ISSUE THREAD

**Issue by jsumners** [ansible/ansible-modules-core#3070]
I'm attempting to do `yum update -y --advisory="RHSA-2016:0175"` like so:

```
ansible -i hosts -m command -a 'yum update -y --advisory="RHSA-2016:0175"' --become --ask-become-pass all
```

And it results in:

```
some.system.example.com | FAILED | rc=0 >>
unsupported parameter for module: --advisory
```

This is with Ansible version 2.0.0.2 as installed via MacPorts. The same error occurs when using the `shell` module.

**Comment by jsumners** [comment]
I closed this issue last night because it was late and I thought I was doing something wrong. I have re-checked this morning and find that the issue is real. Example:

``` bash
$ # this one works
$ ansible -i hosts -m command -a 'ls -lh /tmp' all
$ # this one reports the 'unsupported parameter' error
$ ansible -i hosts -m command -a 'ls -lh --color=always /tmp' all
```

**Comment by vgrivel** [comment]
Hi, 
I have the same problem. I've install ansible via pip and also try via brew, but I have the same issue.

**Comment by bcoca** [comment]
have you tried?:
`ansible -i hosts -m command -a 'ls -lh --color\=always /tmp' all`

**Comment by jsumners** [comment]
@bcoca that works, but I don't know why I would have every thought to try that. The command is enclosed in non-expanding quotes and should, as far as I understand it, be passed directly into the command module as the "command" to execute (i.e. not be interpreted or parsed for more options).

**Comment by bcoca** [comment]
This has to do with the options `creates=` and `warn=` that need to be extracted from the 'raw command string', need to sync with rest of team on how we want to handle this (update docs, warning, etc)

**Comment by jimi-c** [comment]
I agree this is a bug. When parsing things which may have an equal in them, we should ignore k=v things where the `k` part is not one of the valid param fields for command/shell/script.

**Comment by jimi-c** [comment]
One work around for this is to escape the equals, as follows:

<pre>
# ansible -m command -a "echo foo\=bar bam\=baz" localhost -vvv
Using /etc/ansible/ansible.cfg as config file
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'
localhost | SUCCESS | rc=0 >>
foo=bar bam=baz
</pre>

I'll look at making exceptions for the command/shell/script/raw modules though, so this isn't necessary.

**Comment by jimi-c** [comment]
Fixed via https://github.com/ansible/ansible/commit/ae21d98955f0d7367ea94610c14e66b78c7ad4ca, which was actually a much easier fix than I expected.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
