### ISSUE TITLE
git: version=<sha1> does not check out the requested SHA1

### ISSUE THREAD

**Issue by rohanpm** [ansible/ansible-modules-core#313]
Issue Type: Bug Report

Ansible Version: ansible 1.8 (devel 0990a71ab5) last updated 2014/11/13 08:26:52 (GMT +1000)

Environment: Fedora 20

Summary: Passing a SHA1 as the "version" argument to the git module doesn't check out that SHA1 as the docs say it should.

Steps To Reproduce:

```
rm -rf ~/clone-test
ansible localhost -c local -m git -a 'repo=https://github.com/ansible/ansible-modules-core dest=~/clone-test version=710b7b9aba4767776d536849573ddce816b0c8c4'
```

Expected Results:

~/clone-test now contains a clone of ansible-modules-core with HEAD and working tree set to 710b7b9aba4767776d536849573ddce816b0c8c4

Actual Results:

Module outputs:

```
localhost | success >> {
    "after": "3a967c80059f8c33fea1cb8628e6ae174e9e8c2f",
    "before": null,
    "changed": true
}
```

...and 3a967c80059f8c33fea1cb8628e6ae174e9e8c2f has been checked out, (which is the latest "devel" branch at time of writing).

Additional info:

This seems to be a regression since ansible 1.7.2.  The same procedure works OK for me with that version.

**Comment by rohanpm** [comment]
Reverting 63e81cfc2e0c3c07245342cd41a0ba147eac55be fixes the problem.

**Comment by abadger** [comment]
Thanks for the report!  My fix for submodules didn't properly keep track of whether the git repo was updated on initial clone so the requested version wasn't checked out in that case.  Should be fixed by the above commit.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
