### ISSUE TITLE
syncronize regression between 2.0.0.2 and 2.0.1.0

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible-modules-core#3136]
##### Issue Type:

- Bug Report
##### Plugin Name:

synchronize
##### Ansible Version:

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

  ANSIBLE_CONFIG = {toxinidir}/playbooks/ansible.cfg
##### Environment:

Both ubuntu-trusty and centos-7
##### Summary:

After upgrading to ansible 2.0.1.0 a regression was found with an existing role. 

```
TASK [windmill.nginx : Rsync nginx configuration.] *****************************
fatal: [jenkins01]: FAILED! => {"changed": false, "failed": true, "msg": "Could not determine controller hostname for rsync to send to"}
```
##### Steps To Reproduce:

Setup ubuntu-trusty or centos-7 VM

```
git clone https://github.com/openstack/windmill
cd windmill
tox -edeploy
```

That will provision your localhost and demo the breakage.

Here is the role being used: https://github.com/openstack/ansible-role-nginx/blob/master/tasks/config.yaml#L33
##### Expected Results:

role to work as expected with 2.0.0.2

```
TASK [windmill.nginx : Rsync nginx configuration.] *****************************
changed: [jenkins01]
```

http://logs.openstack.org/30/280430/7/check/gate-windmill-deploy-centos7-nv/184cc1f/console.html#_2016-02-18_16_38_49_774
##### Actual Results:

```
TASK [windmill.nginx : Rsync nginx configuration.] *****************************
fatal: [jenkins01]: FAILED! => {"changed": false, "failed": true, "msg": "Could not determine controller hostname for rsync to send to"}
```

http://logs.openstack.org/81/285081/2/check/gate-windmill-deploy-centos7-nv/1e84964/console.html#_2016-02-28_21_01_55_143

**Comment by bcoca** [comment]
I'm not sure this is a 'regression' as much as a fix for the broken behavior added in 2.0, currently the module is now compatible with what was there in 1.9 as 2.0 tried to introduce new features but broke existing capabilities, copying @abadger as he knows the specifics on this.

**Comment by pabelanger** [comment]
It should be noted the role work on 1.9.4 too.  So currently both 1.9.4 and 2.0.0.2 work as expect, 2.0.1.0 has the regression.

```
PLAY [jenkins] **************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [jenkins01]

TASK: [Update apt cache.] ***************************************************** 
ok: [jenkins01]

TASK: [{{ rolename }} | Include OS-specific variables.] *********************** 
ok: [jenkins01]

TASK: [{{ rolename }} | Install nginx package.] ******************************* 
changed: [jenkins01]

TASK: [{{ rolename }} | Copy nginx configuration file.] *********************** 
changed: [jenkins01]

TASK: [{{ rolename }} | Create custom configuration directory.] *************** 
changed: [jenkins01]

TASK: [{{ rolename }} | Rsync nginx configuration.] *************************** 
changed: [jenkins01 -> 127.0.0.1]

TASK: [{{ rolename }} | Enable nginx service.] ******************************** 
ok: [jenkins01]

NOTIFIED: [{{ rolename }} | Validate nginx] *********************************** 
changed: [jenkins01]

NOTIFIED: [{{ rolename }} | Restart nginx] ************************************ 
changed: [jenkins01]

PLAY RECAP ******************************************************************** 
jenkins01                  : ok=10   changed=6    unreachable=0    failed=0
```

```
$ ansible-playbook --version
ansible-playbook 1.9.4
  configured module search path = None
```

**Comment by pabelanger** [comment]
After talking on IRC and looking at code, this appears to originate with https://github.com/ansible/ansible/pull/13968

**Comment by abadger** [comment]
I wasn't able to get your tox environment to run successfully so I'm not able to fully figure out what the requirements you're working under are.  However, this morning I did figure out the general way that this is being hit and a couple workarounds that you can try.

We're hitting this when the action plugin thinks we're ssh'ing to a remote host and the remote host does not have the SSH_CLIENT or SSH_CONNECTION environment variables.  I noticed that the inventory file in the windmill checkout aliases several hosts to localhost.  Ansible has an implicitly defined localhost hosts entry that does not use ansible_connection=ssh; instead it uses ansible_connection=local.  Somewhere Ansible is getting confused and uses the local connection type to connect but thinks that the connection is being made over ssh and so decides to scan for SSH_CLIENT which does not exist.

there's a couple workarounds that can be used to un-confuse ansible that can be applied to the inventory file:

```
jenkins ansible_host=127.0.0.2
```

This workaround works because it uses a host that Ansible doesn't implicitly recognize as localhost.  This is also probably a clue as to where in the logic ansible is getting confused.

```
jenkins ansible_host=localhost ansible_connection=local
```

This works because it explicitly tells ansible that this host uses connection=local.  It's probably the least hacky workaround as it's not relying on ansible internals but merely giving those internals more information with which to make a decision.

Hope the workarounds help.  I'll leave this open as we try to find a solution in code so things just work out of the box.

**Comment by abadger** [comment]
Okay, that above Pull Request to the main ansible/ansible repository appears to fix this problem in code.  Test it out if you can.  I'll hopefully get a review on it early next week and then cn merge to devel and the stable-2.0 branches.
