### ISSUE TITLE
apt autoremove not working

### ISSUE THREAD

**Issue by premctl** [ansible/ansible-modules-core#3200]
i'm running this task

```
- apt: name=apache2 state=absent autoremove=yes
  become: yes
```

which gives this output

> fatal: [172.28.128.5]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"autoremove": "yes", "name": "apache2", "package": "apache2", "state": "absent"}, "module_name": "apt"}, "msg": "unsupported parameter for module: autoremove"}

**Comment by sivel** [comment]
It looks like we need to update the docs.  This was just added 1 month ago, so it isn't in any released version yet.  The `version_added` should read `2.1`.

**Comment by premctl** [comment]
exactly, I was looking for version number there and found nothing.

**Comment by sivel** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This change will not immediately reflect on the documentation site until the next docs build occurs.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
