### ISSUE TITLE
service: state=reloaded starts service if not running

### ISSUE THREAD

**Issue by ingmar** [ansible/ansible-modules-core#350]
This differs from what `service mydaemon reload` or `/etc/init.d/mydaemon reload` do in most cases (because these usually try to send SIGHUP to a running process and do nothing if they can't find one).

For example when using Nginx, `service nginx reload` will not do anything if Nginx isn't already running. Ansible, instead of replicating this behaviour, [starts the service](https://github.com/ansible/ansible-modules-core/blob/devel/system/service.py#L295) when asked only to reload and it isn't found running.

**Comment by ingmar** [comment]
Further research shows that this behavioiur has [apparently been changed](https://github.com/ansible/ansible/issues/4448) without much discussion taking place. I also think what @PriceChild [describes](https://github.com/ansible/ansible/issues/4448#issuecomment-58637762) is the right way, meaning _"it should be up to the init script what happens when a reload is called for."_

There is currently no way of preventing Ansible from starting a service when only a reload was requested (other than terrible hacks abusing the `pattern` option).

**Comment by ScottKevill** [comment]
I agree that this change was too hasty and not a good decision. Encountered this today and was quite surprised to see a couple of services started when they were supposed to remain not running until later activated. Anyone coming to this with previous experience of SysV scripts or systemctl reload (on Red Hat at least) will not be expecting it.

I don't see any reason these two behaviours should be combined. If he wants to ensure the service is started if not already running, he should do exactly that, with a state=started.

As it is now, I can't modify a config file without it starting the intentionally-not-running service unless I use a different playlist/task without notifying the reload handler. The higher level operation is "update the config file". Reloading is just a side-effect. If the service is not already running, then the reload is unnecessary because the config will be loaded anyway by its initialisation when the service is actually started.

**Comment by pabelanger** [comment]
Ugh, just hit this too. Now I need to hackup my playbook

**Comment by MatthiasLohr** [comment]
Same here... could anyone please fix that?

**Comment by pabelanger** [comment]
Well, I can get a revert up, but likely need to discuss this on the ML.

**Comment by jctanner** [comment]
Testcase ...

```
$ cat inventory 
foohost ansible_ssh_host=localhost

$ cat site.yml 
- hosts: foohost
  gather_facts: False
  connection: local
  sudo: yes
  tasks:
    - service:
        name: nginx
        state: reloaded

$ cat test.sh 
#!/bin/bash

sudo systemctl stop nginx.service

ansible-playbook -i inventory -vvvv -c local site.yml
RC=$?
if [[ $RC != 0 ]]; then
    exit 99
fi

echo "## Checking process table ..."
ps aux | fgrep -i nginx

echo "## Checking final state ..."
sudo systemctl stop nginx.service
RC=$?
echo "## RC==$RC"
if [[ $RC != 0 ]]; then
    echo "## not running"
    exit 0
else
    echo "## running"
    exit 1
fi
```

**Comment by jctanner** [comment]
Results ...

| version | el6 final state | el7 final state |
| :-: | --- | --- |
| 0.0.1 | 99 | 99 |
| 0.0.2 | 99 | 99 |
| 0.01 | 99 | 99 |
| 0.3 | 99 | 99 |
| 0.3.1 | 99 | 99 |
| 0.4 | 99 | 99 |
| 0.4.1 | 99 | 99 |
| 0.5 | 99 | 99 |
| 0.6 | 99 | 99 |
| 0.7 | 99 | 99 |
| 0.7.1 | 99 | 99 |
| 0.7.2 | 99 | 99 |
| 0.8 | 99 | 99 |
| v0.9 | 99 | 99 |
| v1.0 | 99 | 99 |
| v1.1 | 99 | stopped |
| v1.2 | 99 | stopped |
| v1.2.1 | stopped | stopped |
| v1.2.2 | stopped | stopped |
| v1.2.3 | stopped | stopped |
| v1.3.0 | stopped | stopped |
| v1.3.1 | stopped | stopped |
| v1.3.2 | stopped | stopped |
| v1.3.3 | stopped | stopped |
| v1.3.4 | stopped | stopped |
| v1.4.0 | running | running |
| v1.4.1 | running | running |
| v1.4.2 | running | running |
| v1.4.3 | running | running |
| v1.4.4 | running | running |
| v1.4.5 | running | running |
| v1.5.0 | running | running |
| v1.5.1 | running | running |
| v1.5.2 | running | running |
| v1.5.3 | running | running |
| v1.5.4 | running | running |
| v1.5.5 | running | running |
| v1.6.0 | running | running |
| v1.6.1 | running | running |
| v1.6.10 | running | running |
| v1.6.2 | running | running |
| v1.6.3 | running | running |
| v1.6.4 | running | running |
| v1.6.5 | running | running |
| v1.6.6 | running | running |
| v1.6.7 | running | running |
| v1.6.8 | running | running |
| v1.6.9 | running | running |
| v1.7.0 | running | running |
| v1.7.1 | running | running |
| v1.7.2 | running | running |
| v1.8.0 | running | running |
| v1.8.1 | running | running |
| v1.8.2 | running | running |
| v1.8.3 | running | running |
| v1.8.4 | running | running |
| v1.9.0-0.1.rc1 | running | running |
| v1.9.0-0.2.rc2 | running | running |
| v1.9.0-1 | running | running |
| v1.9.0-2 | running | running |
| v1.9.0.1-1 | running | running |
| v1.9.1-0.1.rc1 | running | running |
| v1.9.1-0.2.rc2 | running | running |
| v1.9.1-0.3.rc3 | running | running |
| v1.9.1-0.4.rc4 | running | running |
| v1.9.1-1 | running | running |
| v1.9.2-0.1.rc1 | running | running |
| v1.9.2-0.2.rc2 | running | running |
| v1.9.2-1 | running | running |
| v1.9.3-0.1.rc1 | running | running |
| v1.9.3-0.2.rc2 | running | running |
| v1.9.3-0.3.rc3 | running | running |
| v1.9.3-1 | running | running |
| v1.9.4-0.1.rc1 | running | running |
| v1.9.4-0.2.rc2 | running | running |
| v1.9.4-0.3.rc3 | running | running |
| v1.9.4-1 | running | running |
| v1.9.5-0.1.rc1 | running | running |
| v1.9.5-1 | running | running |
| v1.9.6-0.1.rc1 | running | running |
| v1.9.6-1 | running | running |
| v2.0.0-0.6.rc1 | running | running |
| v2.0.0-0.7.rc2 | running | running |
| v2.0.0-0.8.rc3 | running | running |
| v2.0.0-0.9.rc4 | running | running |
| v2.0.0.0-1 | running | running |
| v2.0.0.1-1 | running | running |
| v2.0.0.2-1 | running | running |
| v2.0.1.0-0.1.rc1 | running | running |
| v2.0.1.0-0.2.rc2 | running | running |
| v2.0.1.0-1 | running | running |
| v2.0.2.0-0.1.rc1 | running | running |
| v2.0.2.0-0.2.rc2 | running | running |
| v2.0.2.0-0.3.rc3 | running | running |
| v2.0.2.0-0.4.rc4 | running | running |
| v2.0.2.0-1 | running | running |
| v2.1.0.0-0.1.rc1 | running | running |

**Comment by jctanner** [comment]
Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational. Let's explain what we're thinking:
- The behavior for reloaded has always been the same: start the service if stopped. (see test results above)
- The module docs for service state that "`reloaded' will always reload"
- https://github.com/ansible/ansible/commit/40574c19382cfbd321f5a4bf7afee154fa2a8d22 was made to restore the historical behavior after it was mistakenly changed.
- Changing the behavior of reloaded is not something we should decide in a bug report.

As such, we're going to close this ticket. However, we're open to being corrected, should you wish to discuss. You can stop by one of our two mailing lists to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by ScottKevill** [comment]
@jctanner
- The behaviour for reloaded has **NOT** always been the same. Your own test case shows it changed in 1.4.0. This issue has always been referring to that change and references ansible/ansible#4448 where the hasty decision was made. The fact that it has now been left unaddressed for so long doesn't mean it has always been that way.
- Changing the behaviour of reloaded in a bug report is exactly what you did in ansible/ansible#4448 -- without any discussion.

Yes, you don't monitor comments on closed tickets, but this is for the benefit of others who find this later.

I still maintain that this was a non-intuitive (and dangerous) behaviour change compared with what a user would expect, and users clearly keep bumping into it (recent comments on #2693 as well).

I ended up having to use this ugly hack for notify handlers (at the time, there was some reason why Ansible wouldn't parameterise the service name, I haven't tried recently):

```
  - name: reload sshd
    command: /usr/bin/systemctl -q reload sshd
    register: reload_result
    ignore_errors: True
    changed_when: "reload_result.rc == 0"
```
