### ISSUE TITLE
Support for --all-databases

### ISSUE THREAD

**Issue by ecv** [ansible/ansible-modules-core#369]
Remove name/db argument requirement from mysql_db.py, so that we can dump and import --all-databases.

**Comment by ecv** [comment]
7d59e895358c637bf6c62c56cf7f4246a320a924

**Comment by Jmainguy** [comment]
See https://github.com/ansible/ansible-modules-core/pull/45 as another implementation of --all-databases.

**Comment by abadger** [comment]
#45 has been merged so going to close this now.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
