### ISSUE TITLE
docker_image doesn't use tag to match images

### ISSUE THREAD

**Issue by leonty** [ansible/ansible-modules-core#3719]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_image module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/opt/ansible_modules/']
```
##### OS / ENVIRONMENT

Ubuntu Server 16.04 
##### SUMMARY

docker_image doesn't build an image if another one with the same name already exist, no matter what the tags are. 
##### STEPS TO REPRODUCE

1) Create on the target machine a folder "/tmp/test" with the only file "Dockerfile" with the following contents:

```
FROM scratch
ADD Dockerfile /
```

2) From the control machine where Ansible is installed run: 

```
$ ansible target -m docker_image -a "name=myimage tag=v1 state=present path=/tmp/test"
```

The result is the new image description with the task state as "changed=true":

```
dev | SUCCESS => {
    "actions": [
        "Built image myimage:v3 from /tmp/test"
    ],
    "changed": true,
...[skipped]
```

3) Repeat the command, changing the tag (notice that this is not a simple retagging, but building another image, probably with different content):

```
$ ansible target -m docker_image -a "name=myimage tag=v2 state=present path=/tmp/test"
```

The result is skipping the task with the status "changed=false":

```
dev | SUCCESS => {
    "actions": [],
    "changed": false,
    "image": {}
}
```
##### EXPECTED RESULTS

On the 3rd step it's expected that another image with the newer tag is created.
##### ACTUAL RESULTS

The 3rd step output with high verbosity:

```
dev | SUCCESS => {
    "actions": [],
    "changed": false,
    "image": {},
    "invocation": {
        "module_args": {
            "api_version": null,
            "archive_path": null,
            "cacert_path": null,
            "cert_path": null,
            "container_limits": null,
            "debug": false,
            "docker_host": null,
            "dockerfile": null,
            "filter_logger": false,
            "force": false,
            "http_timeout": null,
            "key_path": null,
            "load_path": null,
            "name": "myimage",
            "nocache": "False",
            "path": "/tmp/test",
            "pull": true,
            "repository": null,
            "rm": true,
            "ssl_version": null,
            "state": "present",
            "tag": "v3",
            "timeout": null,
            "tls": null,
            "tls_hostname": null,
            "tls_verify": null,
            "use_tls": "no"
        },
        "module_name": "docker_image"
    }
}
```

**Comment by leonty** [comment]
More details, even worse: 
Assume we used force=true on the 3rd step. Ok, that worked and now there are 2 tagged images:
myimage:v1
myimage:v2

The next, 4th step (adding one more image with a new tag) finishes with error:

```
$ ansible target -m docker_image -a "name=myimage tag=v3 state=present path=/tmp/test"
dev | FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "Registry returned more than one result for myimage:v3"
}
```

This behavior actually breaks the very essential use of Docker - continious integration as building a test application image for every new repository commit. Please fix it so that 2.1.0.0 be usable.

**Comment by MrMMorris** [comment]
@bcoca is the docker module being rewritten? https://github.com/ansible/ansible-modules-core/pull/3710 

I also have 2 open tickets that make the docker module essentially broken for the most common use cases:

https://github.com/ansible/ansible-modules-core/issues/3219
https://github.com/ansible/ansible-modules-core/issues/3231

**Comment by rcoup** [comment]
Not sure if it's related... (Ansible 2.1.0)

```
- docker_image:
    name: "quay.io/org/repo:version1"
```

looks for `quay.io/org/repo:latest` instead of the tag from the image name. Despite the docs saying "When pushing or pulling an image the name can optionally include the tag by appending ':tag_name'."

To get it to work:

```
- docker_image:
    name: "quay.io/org/repo:version1"
    tag: "version1"
```

**Comment by sandrinr** [comment]
I am experiencing the same behaviour with `docker_image`. In order to still be able to build docker images the way I would expect from `docker_image` I am currently using this workaround:

```
- shell: docker images image-name:<tag> | grep -q image-name
  register: image_name_image_result
  changed_when: image_name_image_result.rc != 0
  failed_when: False
- command: docker build --tag=image-name:<tag> "path/to/build/dir"
  when: image_name_image_result.rc != 0
```

**Comment by tkinz27** [comment]
So although I am just trying to pull images from an artifactory docker registry, I think I'm running into the same bug. Basically I have a task file like this...

```
- name: pull jenkins docker image from artifactory - {{jenkins_slave_image}}:{{jenkins_slave_def.container_version}}
  # https://github.com/ansible/ansible-modules-core/issues/3719 means force must be true
  docker_image: name={{jenkins_slave_image}} tag={{jenkins_slave_def.container_version}} force=yes
```

Where the `jenkins_slave_image` = `artifactoryhost:8000/jenkins/slave` and `jenkins_slave_def.container_version` = `centos7-0.1.0` or `trusty-0.1.0`. I made some updates to the dockerfiles, built and pushed to our registry server so now all my `jenkins_slave_def.container_version` = `centos7-0.1.1` for instance. 

After rerunning the playbook with the new tags, I get the same error as above
`"Registry returned more than one result for artifactoryhost:8000/jenkins/slave:centos7-0.1.1"`

After poking around I think I have found the source of the problem. In the [module_utils/docker_common.py::_find_image()](https://github.com/ansible/ansible/blob/0ada7eae5e3049e82dcb49acb8405e95e42bb1a3/lib/ansible/module_utils/docker_common.py#L434-L438) function ansible searches docker for all images matching the image name (regardless of tag name), then manually searches for the tag if a tag is provided. In my case the image+tag combo does not exist (was expecting ansible to recognize this and pull the newer tag from the registry), but since that never makes a match the loop is never broken and all the images are returned causing the error in the `find_images()` function. 

I hope this helps resolve this issue. I think you can just do something like this

```
if tag:
    name = "{}:{}".format(name, tag)
```

at the beginning of the function (which worked for me). But the comment mentions some problems with explicitly looking for the tag, so I'm going to assume that solution is not valid.

Anyways, hopefully this helps.
Tony

P.S I'm using ansible from pip

```
[root@3dc711152b0d stuff]# ansible --version
ansible 2.1.0.0
```

I did my debugging by setting ANSIBLE_KEEP_REMOTE_FILES=1 and making modification in the debug_dir. I wanted to mention, the new zipped up package that ansible is doing is really cool, and the explode / execute commands make working with the package really easy. Thank you for adding those types of features, they are invaluable.

**Comment by relistan** [comment]
I'm seeing the exact same issue, and it seems to occur somewhat sporadically. Will be working and then I'll update a tag and it won't work any more. Manually pulling the images with `ansible -m shell` calling out to Docker first seems to clear it up, sometimes for a few deploys (even with different tags). 

Also running 2.1.0.0.

**Comment by hakamairi** [comment]
If I understood the mergerequest correctly this fix is going to be part of 2.2.0 version (was merged to devel), could it also be part of any intermediate 2.1.x release?

**Comment by daniilyar-confyrm** [comment]
Same issue exists in docker_container module. I can confirm that https://github.com/ansible/ansible/issues/16680 fixed both docker_image and docker_container modules.

Is there any chance to get this fix into 2.1.X ?

**Comment by ferrarimarco** [comment]
Same issue here with 2.1.1.0. Any updates? Thanks

**Comment by gbmeuk** [comment]
+1

**Comment by nuklea** [comment]
The same with 2.1.2.0 when try missing tag:
Registry returned more than one result for ns/image:tag

**Comment by Hubbitus** [comment]
Does this fix present in v2.2.0.0-0.1.rc1?

**Comment by tntC4stl3** [comment]
+1
Already encountered two issues which relate to docker, one in `docker-image` and another in `docker-container`.
Both were fixed but didn't apply to 2.1.x yet....

**Comment by reiz** [comment]
I'm getting the same error with Ansible  2.1.2.0. Now I'm building my Docker images like this: 

```
name: build crawlj docker image
shell: cd /opt/docker_crawlj; docker build -t versioneye/crawlj:{{docker_crawlj_version}} .
```

That's the good thing about Ansible. If a module is broken you can just use the shell module :-)

**Comment by hakamairi** [comment]
Another workaround, a pre step like:

```
  docker:
    name: "some_name"
    image: "full_image_name:with_tag"
    pull: always
```

**Comment by gbmeuk** [comment]
There is a patch for this: https://github.com/ansible/ansible/pull/16680/files

Remember to move docker_common.pyc out of the way

**Comment by benoahriz** [comment]
same issue encountered.  Using a manual pull using shell module to work around :(

**Comment by ide** [comment]
As of Ansible 2.2.0 (now available via pip) the `docker_image` module can pull images successfully. Ex:

``` diff
   - name: Pull the Docker image
-    shell: docker pull "{{ docker.image }}":"{{ docker.tag }}"
-    register: docker_pull_result
-    changed_when: "'Status: Downloaded newer image for' in docker_pull_result.stdout"
+    docker_image:
+      name: "{{ docker.image }}"
+      tag: "{{ docker.tag }}"
```
