### ISSUE TITLE
--check skips instances of 'command', even with creates= and/or removes=

### ISSUE THREAD

**Issue by hispirus** [ansible/ansible-modules-core#372]
##### Issue Type:

Bug Report, since even though 'command' idempotency can not be inferred in the general case, it can be in the presence of creates= and/or removes=.
##### Ansible Version:

commit 5af8d55b0365a5c3278c43b5424bf5f2ddf897b8
##### Environment:

N/A; commands/command.py does not contain 'supports_check_mode' in any environment.
##### Summary:

When a playbook that calls the 'command' module with creates= and/or removes= is run in check mode, that task is skipped (yielding no usable information) even though Ansible could unambiguously determine that the task would not be run, thus not introduce any changes to the environment.

Generally, it is a good idea to skip command module tasks while in check mode, as being able to find out, without exceptions, whether a command would make any state changes is fundamentally impossible. The addition of creates= and/or removes= turns this undecidable problem into a semidecidable one: if the respective conditions are fulfilled, we know that the task will not run. If they aren't, we know nothing. This suggests that a module should be able to yield a 'skip me' to the task runner itself.

There may be other design solutions.

Skipping the remaining sections since I don't expect them to be able to sensibly constrain the design space.

**Comment by mpdehaan** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:
- the command should run if creates andremoves are not satisfied

However, however what is happening is that:
- we're always skipping, we have to skip if creates/removes is not fulfilled because we must skip commands
- we still skip if the creates/removes is "matched", because that would skip it anyway
- the result is that we still don't execute commands
  In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by hispirus** [comment]
It is indeed possible that you misunderstood the issue at hand. Of course the command should not run in `--check` mode if the file referenced by `creates=` exists and/or the file referenced by `removes=` doesn't. Any of these three conditions are sufficient on their own. This is well-understood behavior and not very interesting by itself.

However, it is not currently possible to deduce from Ansible's output whether a command would have caused a state change on the host an Ansible playbook is applied to. As I pointed out, this is impossible to infer if the command would actually be run, but not if it would not be run even outside of `--check` mode. What this boils down to is that a `--check` shows a 'skipped' play even though it could display an 'ok' one.

**Comment by jorrit** [comment]
I agree with hispirus. It would be very useful when commands/scripts/etc. with removes/creates clauses would run the removes/creates checks when `--check` is invoked.
