### ISSUE TITLE
cannot connect to S3 from RHEL-5

### ISSUE THREAD

**Issue by imvitaliy** [ansible/ansible-modules-core#3726]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

s3
##### ANSIBLE VERSION

```
2.0.2.0
```
##### OS / ENVIRONMENT

RHEL-5
##### SUMMARY

can't run "module_name": "s3", only in Rhel-5
##### STEPS TO REPRODUCE

```
- name: Get package from s3
  s3: bucket=name object={{pkg }} dest=/tmp/{{ pkg }} aws_access_key={{ aws_access_key_id }} aws_secret_key={{ aws_secret_access_key_id }} mode=get
```

##### EXPECTED RESULTS

should download package from S3
##### ACTUAL RESULTS

```
fatal: [52.39.32.137]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "s3"}, "module_stderr": "", "module_stdout": "  File \"/root/.ansible/tmp/ansible-tmp-1462959054.23-157331921236549/s3\", line 326\r\n    except SSLError as e:\r\n                     ^\r\nSyntaxError: invalid syntax\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by abadger** [comment]
Unfortunately, the s3 ansible module depends on the boto python library which requires python >= 2.6.  Our policy is to allow using python-2.6 syntax in a module if it has dependencies which also require python-2.6.  Since RHEL-5 ships with python-2.4, this module will not work with the stock python on RHEL-5.  You can find requirements information in module documentation.  For instance, the s3 documentation is here: http://docs.ansible.com/ansible/s3_module.html

Although far from ideal, a workaround would be to download the file to the controller machine using the s3 module and then push it to the rhel5 boxes using the copy module.  Migrating the RHEL5 box to a newer distro version is another option but I know how old installs can linger for many years so that may be infeasible for your site to do that just now.

**Comment by imvitaliy** [comment]
I was compile python2.6 and install boto but it was still without working
