### ISSUE TITLE
Yum upgrade using local RPM does nothing

### ISSUE THREAD

**Issue by ppersad** [ansible/ansible-modules-core#3807]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

yum
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using the yum module to upgrade (my-rpm-1.0 -> my-rpm-1.1) an already installed RPM from a local rpm file, I get the following output:

```
my.host.net | SUCCESS => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "conf_file": null, 
            "disable_gpg_check": false, 
            "disablerepo": null, 
            "enablerepo": null, 
            "exclude": null, 
            "install_repoquery": true, 
            "list": null, 
            "name": [
                "/tmp/my-rpm.rpm"
            ], 
            "state": "present", 
            "update_cache": false, 
            "validate_certs": true
        }, 
        "module_name": "yum"
    }, 
    "msg": "", 
    "rc": 0, 
    "results": []
}
```

No changes were made and installed RPM is still the old version.

This bug was caused by commit c8222bc8db31c4b46645912c0f13c1632333eae4 fixing issue #1452.  At packaging/os/yum.py:576, when getting the package name for localpkg, the call to local_nvra was switched to local_name.  As a result, when deciding if an install is necessary, instead of comparing the rpm name-version-release-arch only the name is compared.
##### STEPS TO REPRODUCE
1. Get two rpms of different version for the same package
2. Place them in /tmp/v1.rpm and /tmp/v2.rpm on the target host
3. Run: ansible <target-host> -m yum -a "name=/tmp/v1.rpm state=present"
4. Run: ansible <target-host> -m yum -a "name=/tmp/v2.rpm state=present"
5. Run on target host: rpm -q <package name>
##### EXPECTED RESULTS

rpm -q should show the higher version number
##### ACTUAL RESULTS

rpm -q shows the lower version number

**Comment by jctanner** [comment]
Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you. This will also be included in the next major release.

The testcase outline in the issue body will still fail to update the rpm, but if you change the second task to state=latest, the desired effect will occur.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
