### ISSUE TITLE
junos_facts - config parameter should have a default value

### ISSUE THREAD

**Issue by dgarros** [ansible/ansible-modules-core#3878]
##### COMPONENT NAME

module : junos_facts

```
network/junos_facts.py
```
##### ANSIBLE VERSION

2.1.0.0
##### OS / ENVIRONMENT

Mac OS 10.11.5
##### SUMMARY

Currently the parameter `config` for junos_facts is mandatory and do not have a default value
I think it would be better to set a default value to `false` and not make this parameter mandatory.

Playbooks will be simplified

I'm happy to send a pull request for it, but I wanted to discuss this change before

**Comment by alikins** [comment]
The commit https://github.com/ansible/ansible-modules-core/commit/a6dc526570f6b4bfddcb106998a25d5dc150e4f3 seems to have changed this.

It's a little hard to say, but since the commit message doesn't mention changing if 'config' is required or not, I suspect that may be unintended.

@privateip should 'config' be required here?

**Comment by dgarros** [comment]
Thanks :)
