### ISSUE TITLE
Yum task reports as "skipping", but silently fails underneath for missing package

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible-modules-core#3891]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

yum
##### ANSIBLE VERSION

v2.0.2.0
##### SUMMARY

If you have a yum task that installs a bunch of packages, and one of the package is somehow not available in the repositories. The task reports itself as "skipping", however it simply fails in reality and the playbook stops with `NO MORE HOSTS LEFT`.

When increasing verbosity, the task clearly failed `{"failed": true}`, and the message is `{"msg": "No Package matching '...' found available, installed or updated", "rc": 0}`...

**Comment by augustineas** [comment]
This bit me as well. A very related issue was reported at the "ansible" level rather than at the module repo level in ansbile bug #15027, but it looked like the submitted never reported it here.

It seems that when the "yum" module is used with the "with_items" directive, that it will report "skipping" in most (all?) cases, whether or not there is a "fatal" or a "changed" or if all items were unchanged.

It would be better for the task to report the "worst" case as the result, for example:
 If all items were unchanged, it should report "ok:".
 If any item was changed, it should report "changed".
 If any item reports "failed" etc, it should report a "failed".
And so on. I am not sure when it would be appropriate for it to report "skipping".

This behavior (reporting "skipping", rather than what actually happened or didn't happen in the task) is new somewhere between 1.9.4 and 2.0.2. It did not behave this way in the last version of 1.9.4. I don't know which sub-version it changed in though.

**Comment by nitzmahone** [comment]
@dagwieers There was a bug when handling failures with arg-squashing that got fixed (IIRC just before 2.1.0) that should have taken care of this. Two things:
- Are you seeing this behavior on current stable-2.1 and devel?
- I assume you're expecting the task to show "failed", not that you want silent success? That's been asked for as well (since it's the way yum itself behaves from cmdline), but we're pretty much all agreed that it's not a great way to go...

**Comment by dagwieers** [comment]
We are seeing this with the v2.0.2.0 release. I will test it with stable-2.1 if you like.

Indeed, if a task fails, it should state it "failed". I don't understand why it would appear to be skipping, even if it succeeded it should not state "skipping" ! Skipping IMO means that no task was executed, but in this case obviously it did perform something. I think it is a bug that the yum module would report "skipping" when the task was not conditional.

**Comment by dagwieers** [comment]
Alright, this problem was _NOT_ in v2.1, but was in v2.0.2.0. In fact I can no longer reproduce this in v2.1. So this issue can be closed. (Let me update the original report to reflect the real issue, despite it being fixed already)
