### ISSUE TITLE
ec2_asg_module docs say state is required but examples never use

### ISSUE THREAD

**Issue by r4j4h** [ansible/ansible-modules-core#4016]
Hope this does not seem too nitpicky! <3
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

ec2_asg
##### ANSIBLE VERSION

> 1.6 (version module was added in)
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The `Options` table indicates that `state` is a required parameter with no default values.

The given examples below do not use a `state` parameter.
##### STEPS TO REPRODUCE

N/A
##### EXPECTED RESULTS

I would expect Ansible to refuse to run the command until I explicitly define the state to be present or absent. Or I expect the documentation to mention that State: present is the default.
##### ACTUAL RESULTS

People seem to be using it fine without ever describing the state option.

I am guessing this means state: present is the default.
## 

I don't mind making the changes and submitting a MR, but I wanted to open an issue to discuss the actual desired end state first.

**Comment by nitzmahone** [comment]
Yeah, it's just a docs/reality mismatch, see https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2_asg.py#L790, the code defines a default of "present", so the docstring in the module should say default: present instead of required: true. Feel free to submit a PR, we'll merge it quickly.

**Comment by jctanner** [comment]
resolved_by_pr https://github.com/ansible/ansible-modules-core/issues/4046
