### ISSUE TITLE
mysql_user throws exception when unable to parse the MySQL grant string

### ISSUE THREAD

**Issue by prydie** [ansible/ansible-modules-core#408]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.1
##### Environment:

Running from elementary OS (Luna) managing FreeBSD 10.1 (via vagrant). However, this bug is platform independent.
##### Summary:

`module` isn't in scope within `database/mysql/mysql_user.py:privileges_get()` and thus on line [#259](https://github.com/ansible/ansible-modules-core/blob/7dd2859f9b13e9df3baa9f2ef947e3630a6e7dbc/database/mysql/mysql_user.py#L259) a `NameError` is thrown.
##### Steps To Reproduce:

Call `mysql_user` with an invalid grant string.
##### Expected Results:

Ansible handles displaying the error elegantly using `fail_json`.
##### Actual Results:

The following exception is thrown:

```
failed: [webserver] => {"failed": true, "item": "", "parsed": false}
SUDO-SUCCESS-mcapibqhjluhnlgwsfllerruaqgbsptx
Traceback (most recent call last):
  File "/home/vagrant//.ansible/tmp/ansible-tmp-1417269216.79-44510609450773/mysql_user", line 2198, in <module>
    main()
  File "/home/vagrant//.ansible/tmp/ansible-tmp-1417269216.79-44510609450773/mysql_user", line 485, in main
    changed = user_mod(cursor, user, host, password, priv, append_privs)
  File "/home/vagrant//.ansible/tmp/ansible-tmp-1417269216.79-44510609450773/mysql_user", line 199, in user_mod
    curr_priv = privileges_get(cursor, user,host)
  File "/home/vagrant//.ansible/tmp/ansible-tmp-1417269216.79-44510609450773/mysql_user", line 259, in privileges_get
    module.fail_json(msg="unable to parse the MySQL grant string")
NameError: global name 'module' is not defined
```

**Comment by abadger** [comment]
I've just pushed a fix to the error handling so that it returns a nice error message instead of creating a traceback.  Is there a separate issue open for the mysql grant that ansible is unable to parse?

**Comment by abadger** [comment]
Commit with the traceback changed into an error message: 1cab3076495f4e6699df5a784500942260220e66

**Comment by abadger** [comment]
Closing this as the traceback is now a nicer error message.  If there's anything needed to enhance parsing of the existing grants feel free to open a new bug.  Thanks!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
