### ISSUE TITLE
mysql_user module: wildcard character causes fault

### ISSUE THREAD

**Issue by akuznecov** [ansible/ansible-modules-core#416]
Hello!
##### Issue Type:

Bug report
##### Ansible Version:

1.8
1.8.1
devel
##### Environment:

Managed: Debian 7
##### Summary:

Usage of MySQL wildcard character `%` causes error when no privileges set to user YET
If privileges set with old version of Ansible before (for example, I have tested with 1.7.2), then no problem occurred with 1.8.x, task just passed with `ok:`
After revoking privileges - problem comes again for 1.8.x
##### Steps To Reproduce:

Simple task with wildcard for database names

``` yaml
- name: 'MySQL | Give database privileges to users'
  mysql_user: name={{mysql_user_name}}
              host=localhost
              priv={{project_name}}_%.*:ALL
              state=present
              login_host=127.0.0.1
```
##### Expected Results:

```
TASK: [mysql-databases | MySQL | Give database privileges to users] *********** 
changed: [foo.bar.example.com]
```
##### Actual Results:

```
TASK: [mysql-databases | MySQL | Give database privileges to users] *********** 
failed: [foo.bar.example.com] => {"failed": true, "parsed": false}
SUDO-SUCCESS-jyhgurmmyijjwzwouoobroexnylhcywq
Traceback (most recent call last):
  File "<stdin>", line 2198, in <module>
  File "<stdin>", line 485, in main
  File "<stdin>", line 216, in user_mod
  File "<stdin>", line 318, in privileges_grant
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 159, in execute
    query = query % db.literal(args)
ValueError: unsupported format character '`' (0x60) at index 22

FATAL: all hosts have already failed -- aborting
```

**Comment by abadger** [comment]
Looking at this, there is a bug in the code but I think in addition to fixing that bug you're also going to have to update your playbook to specify '%%' instead of '%'.

Before 1.8.x we were passing the string in without any quoting which could lead to unexpected commands being sent to your database if, for instance, a role contained a particularly bad query string.  In fixing that, we now pass the table portion of the param through the python-mysql quoting mechanism which is using a format string and provoking this error.  Escaping the % by doubling it in the module parameter should fix that portion (and I just have to fix the bug so that the code expects the escaped % everywhere.)

**Comment by abadger** [comment]
Second look, I think I can preserve backwards compat (so that "{{project_name}}_%:ALL" works).  I'm updating my patch now.

**Comment by abadger** [comment]
If you can test the devel branch of the modules, I think that that commit should fix this without you having to make any changes to your playbook.  If can't test the devel branch, you could take a look at the new integration tests to see if I covered your use case.

Thanks for the report!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by akuznecov** [comment]
Hello!

@abadger thanks a lot for the fix!
just tested devel branch of modules(core,extra) and Ansible itself - could not reproduce this problem anymore!
