### ISSUE TITLE
Allow to validate configuration with `file` module

### ISSUE THREAD

**Issue by thomwiggers** [ansible/ansible-modules-core#4183]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

file module
##### SUMMARY

The `copy` module supports a `validate` instruction. This allows to fast-fail if a broken config is merged. The`file` module does not support this. It would be useful however, e.g. in situations where config files are symlinked in place (e.g. sites-enabled with Apache, nginx on Debian/Ubuntu).

```
#This works
- copy: src="filename" dest="filenamesomewhere" validate="mycommand -t %s"

# this doesn't but would be nice:
- file: src="filename" path="filenamesomewhere" state=link validate="mycommand -t %s"
```

**Comment by bcoca** [comment]
A common misconception is that validate works on the target file, it does NOT. It runs against the temporary file (%s) BEFORE it is copied into place. Since file is not creating a temporary file, it does not make much sense to have validate there.

You just probably want a task:

```
- shell: mycommand -t /path/to/filename
```

which you can ignore_errors/register if you want to continue play and deal with the failure in it.

**Comment by thomwiggers** [comment]
Fair enough
