### ISSUE TITLE
Exception thrown when using the template module with delegate_to/with_items

### ISSUE THREAD

**Issue by jfchevrette** [ansible/ansible-modules-core#456]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.8.2
  configured module search path = None
```
##### Environment:

OS X 10.10 client, RHEL 6.6 managed host
##### Summary:

Using delegate_to and with_items along with the template module results in an Exception.
##### Steps To Reproduce:

**hosts**

```
[mygroup]
198.72.123.172

[othergroup]
198.72.123.172
```

**test.yml**

```
$ cat test.yml
- name: Test delegate_to and with_items
  hosts: mygroup
  tasks:
    - name: shell module
      shell: "hostname -f"
      delegate_to: '{{ item }}'
      with_items: groups.othergroup

    - name: template module
      template: src=testfile.j2 dest=/tmp/testfile
      delegate_to: '{{ item }}'
      with_items: groups.othergroup
```

**testfile.j2**

```
(template content irrelevent)
```
##### Expected Results:

The template module should work with delegate_to/with_items
##### Actual Results:

As the example above shoes, the shell module works (as with other modules) but when using the template module an Exception is thrown.

https://gist.github.com/jfchevrette/a4925e38237d2c7617fe

I guess there is also confusion on whether the template should be using the current playbook host variables/facts or the delegated server's variables?

**Comment by bcoca** [comment]
what exception?

**Comment by jfchevrette** [comment]
@bcoca sorry, I edited the report to include a gist with the verbose log & exception

**Comment by abadger** [comment]
I think this commit implements a fix: https://github.com/ansible/ansible/commit/3269a349f32a2b5c1fc079a2d174e01c541f444b

There was another attempt at a fix on Friday that this overwrites in case you're looking to consume just this patch.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
