### ISSUE TITLE
Ansible 1.8.2, module: file. Can't set permissions on hardlinks.

### ISSUE THREAD

**Issue by iprok** [ansible/ansible-modules-core#468]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

Gentoo amd64, Debian wheezy amd64
##### Summary:

Can't set permissions on hardlinks using file module. follow=yes doesn't help
##### Steps To Reproduce:

file: path=<some hardlink path> owner=root group=root mode=4710
##### Expected Results:

Permissions will be set correctly
##### Actual Results:

error:
msg: src and dest are required for creating links

I think it's totally wrong cause hardlinks are also regular files which permissions and ownership should be able to be changed.

**Comment by mrhjkim** [comment]
I have similar problem. Template is not working if destination file already exist with hard link.
Problem is in ansible/modules/core/files/file.py. os.readlink(path) fails.
if state in ['link','hard']:
            if follow:
                # use the current target of the link as the source
                src = os.readlink(path)

**Comment by abadger** [comment]
Possibly related issue:

https://github.com/ansible/ansible-modules-core/issues/302

**Comment by abadger** [comment]
@iprok The file module is one of the older modules in ansible and some of the code has accumulated various fixes that make it hard to change.  What you're specifically running into here is that the state parameter defaults to the previous state of the file.  That means that since the file is a hardlink, ansible defaults state to a hardlink and thus it thinks that it needs both a src and a path parameter to be specified.

Barring someone rewriting the file module to fix that defaulting behaviour, the workaround is to explicitly state what state you want to apply to the file.  In this case, you don't care that the file is a hardlink, you just want to apply permissions to it.  So you need to specify state=file like this:

```
file: path=/var/tmp/hardlink owner=root group=root mode=4710 state=file
```

In testing whether this worked, we ran across another bug  with hardlinks and the file module.  @bcoca is working on a fix for that which you can see here: https://github.com/bcoca/ansible-modules-core/tree/file_link_permissions

@sysadmin75 We looked at your code too.  We're a tad worried about possible side effects of doing that (like I say, the file module has grown a lot of cruftiness that makes side effects more common).  It seems like a band-aid over the band-aid of defaulting state to the previous state of the file.  We'd like to avoid adding more code that depends on that defaulting behaviour if we can so that we don't make it even more difficult for someone who has the energy to fix it.

**Comment by abadger** [comment]
Additional fix merged: https://github.com/ansible/ansible-modules-core/pull/606

Combining that fix along with explicitly specifying state=file should fix this problem.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
