### ISSUE TITLE
Ansible 1.8.2, module: cron. Make it idempotent when using random time

### ISSUE THREAD

**Issue by iprok** [ansible/ansible-modules-core#470]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

Ansible on Gentoo amd64.
##### Summary:

Bug is discussed in the end of https://github.com/ansible/ansible/issues/6896 . It will be good if have ability to make minute\hour\day\month params of cron module random and keep it idempotent. For example by adding random_minute, random_hour ... boolean parameters.
##### Steps To Reproduce:
- name: cron record
  cron: name="myjob" minute={{ 59 |random }} job="myjob"
##### Expected Results:

Should be idempotent. For example
- name: cron record
  cron: name="myjob" minute={{ 59 |random }} job="myjob" random_minute=true
##### Actual Results:

it's changed every run.

**Comment by bcoca** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:
- First, the random filter is not part of the cron module, you can use one without the other. The way this works is that you are asking for a random value each run, which should change most of the time (otherwise it suggests a problem with randomization).
- This seems to be a feature request or a question on how to achieve creating an initial random value and then keeping track of it across runs. There are ways to do this already and I suggest you post the lists detailed below or ask in the ansible IRC channel.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
