### ISSUE TITLE
uri module could be more lenient in accepting 'json' content types

### ISSUE THREAD

**Issue by bobobox** [ansible/ansible-modules-core#503]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.8.2
##### Environment:

N/A
##### Summary:

The uri module only attempts to parse JSON returned from the http server if the returned content type is identified as "application/json". However, there are APIs out there that return JSON and identify themselves differently: For example, LogicMonitor's API returns JSON with content type "text/json;charset=utf-8".

Thus, the returned JSON is treated as quoted text, which is much less useful (without going through some contortions). 

If the module would instead perhaps look for the string 'json' rather than strictly requiring 'application/json', it would make it more adaptable.
##### Steps To Reproduce:

Perform a GET request against a service that returns JSON formatted text with content type in the header that is something other than "application/json".
##### Expected Results:

The module could either accept several other commonly used 'JSON' content type strings, or could use a regex to find the pattern 'json' in the content type string, and parse the JSON data. The JSON data could then be easily accessed in the returned content.
##### Actual Results:

Returned JSON with a content type string other than "application/json" is treated as a string, requiring some further machinations like using 'copy' and then 'include_vars' to write the content to a temp file and then bring the content back in as facts.

**Comment by abadger** [comment]
Sounds reasonable to add text/json since that's out in the wild still.  I don't think a substring search for "json" is a great idea though.  Since applitcation/json is the standard mime type we should see less of things other than that as time goes on.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
