### ISSUE TITLE
mysql_db fails to re-compress sql files when encountering a failure

### ISSUE THREAD

**Issue by maguiresf** [ansible/ansible-modules-core#616]
When importing a gzipped sql file into a database using the mysql_db module, if something causes the import into the database to fail the module doesn't re-compress the sql file before exiting. In my test case I was trying to import 3 gzip compressed sql files which had to be done in the correct order otherwise they would error. Initially I had the order wrong; once I corrected it my playbook couldn't run due to the original target no longer being present on the server, i.e. the sql file was left uncompressed rather than in it's original compressed state. Looking at the code I suspect that lines 161 and 162 need moving to after line 167.

**Comment by bcoca** [comment]
checked the code, in all cases of compressed file it unzips the original, runs the command and if all is well, rezipps. Need to either do this non destructively (don't delete original zip file) or ensure that rezipp always happens.

**Comment by Jmainguy** [comment]
@maguiresf Ty for reporting this
@bcoca Please test https://github.com/ansible/ansible-modules-core/pull/824 to address this issue

**Comment by Jmainguy** [comment]
@maguiresf #824 has been merged. Can you try latest devel and confirm this can be closed?

**Comment by abadger** [comment]
This has been fixed.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by sigio** [comment]
Why is it unzipping and re-zipping files... just unzip to a temp-location and read that, delete afterwards...
Ran into this as I saw a machine bzipping a large database dump on an import.

On the cmdline i'd just use bzcat file.bz2 | mysql database .... but using the mysql_db module it now uncompressed and then recompresses the file... which takes ages.

For the time being I'll just go back to uncompressed... saves me time both ways

**Comment by Jmainguy** [comment]
@sigio I guess we assumed the admin would want the source to stay intact, I can see the argument for removing it though. @maguiresf What do you think?

**Comment by sigio** [comment]
If you leave the compressed file as is... that would be the intact source... right ?

My situation: copy bzipped dumps to machine, mysql_db import the bzip2...
result: unzipping, importing and re-zipping ....

What i'd expect: unzip to tempfile, import tempfile (or better, unzip to pipe/fifo, import from there)

Because unzipping and re-zipping isn't 'leaving the source file intact', it's trying to make an equivalent source file, but a new one (different timestamp, compression-options, etc)

**Comment by Jmainguy** [comment]
@sigio yeah, that would make more sense to me. I will open a new bug to keep track of this.
