### ISSUE TITLE
pause module does not work with vagrant provisioner when prompt option is used

### ISSUE THREAD

**Issue by tkellen** [ansible/ansible-modules-core#656]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
##### Environment:

OSX
##### Summary:

Ansible fails to run playbooks for Vagrant that utilize the pause module in conjunction with the prompt option.
##### Steps To Reproduce:

Add `- pause: prompt="test"` to a playbook that will be run by vagrant's ansible provisioner.
##### Expected Results:

prompt is shown and playbook continues after it is cleared.
##### Actual Results:

provisioning fails with:

```
TASK: [deploy | pause prompt="test"] ******************************************
fatal: [vagrant] => Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.8.2/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 590, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/Cellar/ansible/1.8.2/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 792, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/Cellar/ansible/1.8.2/libexec/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1025, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/Cellar/ansible/1.8.2/libexec/lib/python2.7/site-packages/ansible/runner/action_plugins/pause.py", line 103, in run
    tcflush(sys.stdin, TCIFLUSH)
error: (25, 'Inappropriate ioctl for device')
```
##### Workaround:

None known at present.

**Comment by gildegoma** [comment]
@tkellen I think that this question might better have been asked first in Vagrant or Ansible mailing list, but let me put my two cents on this topic directly here: 

More generally you can reproduce the same `'Inappropriate ioctl for device'` error outside of Vagrant, by changing `stdin` of your `ansible-playbook` command (e.g. `echo go | ansible-playbook -i ... myplaybook.yml`).

It is a known issue (https://github.com/mitchellh/vagrant/issues/2924) that Vagrant fails to integrate Ansible interactive prompts that are implemented on top of `raw_input` / `readline` python builtins (e.g. non-private variables prompts or the `pause` module with `prompt`). 

I think that the current state of Development for this project is the following:
- From what I could see so far, Ansible user prompts might not be designed to be used with redirected `stdin` and `stdout` channels (to be confirmed by Ansible Project Team).
- Vagrant is by nature a fully automated tool and does not aim at giving (at high development costs) an official support for "user prompts" in its standard workflow.

---

Note that "private" prompts (`--ask-pass`, `--ask-sudo-pass`, `--ask-su-pass` and `--ask-vault-pass`) are working well in combination with Vagrant because these features rely on [getpass](http://python2.7.sourcearchive.com/documentation/2.7.1-1ubuntu4/namespacegetpass_a8b356a7df1eab1b1e6a3b9c8c88eac68.html#a8b356a7df1eab1b1e6a3b9c8c88eac68), which deals with redirected TTYs.

**Comment by bcoca** [comment]
As @gildegoma explains, this seems more like an design incompatibility than a bug. If you are going to use a batch system to run a playbook, you should really not prompt.

**Comment by tkellen** [comment]
Roger that.  Thanks for the information!
