### ISSUE TITLE
unarchive module: Solaris version of 'tar' doesn't support decompression options.

### ISSUE THREAD

**Issue by zystem** [ansible/ansible-modules-core#702]
https://github.com/ansible/ansible/issues/7644
Bug still not resolved.

yeroc commented on 2 Jun 2014
Issue Type:

Bug Report
Ansible Version:

ansible 1.7 (devel 6bc056e) last updated 2014/06/02 14:42:33 (GMT -600)
Environment:

Solaris 10/11
Summary:

The unarchive module assumes gnu tar with support for directly decompressing tgz, bzip & xz compression formats but the Solaris version of tar doesn't support the -z, -j or -J options respectively. It would be great if the unarchive module would fallback to looking for gzip, bzip & xz binaries and using them to handle the decompression.
Steps To Reproduce:

Given a simple unarchive task:
- name: Copy packages...
  unarchive: src="{{ item }}" dest="/tmp" copy=yes
  with_items:
  - "solaris/jdk-7u55-solaris-i586.tgz"
  - "solaris/jdk-7u55-solaris-x64.tgz"

Expected Results:

Expect the file(s) to be unarchived on the destination host.
Actual Results:

failed: [dbload-solaris] => (item=solaris/jdk-7u55-solaris-i586.tgz) => {"failed": true, "item": "solaris/jdk-7u55-solaris-i586.tgz"}
msg: Failed to find handler to unarchive. Make sure the required command to extract the file

**Comment by zystem** [comment]
It is official SUNWgtar package for Solaris 10.
This package provides usr/sfw/bin/gtar binary.
gtar binary support same options as gnu tar.
So unarchive need option tar_binary_name_in_system.

**Comment by abadger** [comment]
I noticed a related problem when I touched this module earlier as well -- depending on the version, gtar may or may not have options to handle xz.  Unfortunately, that one is a bit harder to fix. (Would need to detect failure due to lacking the commandline options to decompress and then fallback to using pipes to uncompress and untar).

For this problem, it seems like we could first try to detect a gtar binary in the PATH.  If that wasn't found, then try to find tar.  Depending on how the PATH is set you may also have to specify that /usr/sfw/bin belongs in PATH via the environment parameter: http://docs.ansible.com/playbooks_environment.html

**Comment by abadger** [comment]
Hey, I think that commit will fix your issue (perhaps with the addition of environment: in your playbook).  I just saw your request for tar_binary_name_in_system comment as well.  I don't think it would be needed here but if you still think it is, please let us know via a new ticket.

Thanks!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
