### ISSUE TITLE
Docker module now generates an error with Docker 1.3.2 and docker-py 0.7.0

### ISSUE THREAD

**Issue by tfhartmann** [ansible/ansible-modules-core#705]
The Docker module now errors with 

``` Shel
msg: Docker API error: client and server don't have same version (client : 1.16, server: 1.15)l
```

It looks like this issue: 
https://github.com/docker/docker-py/issues/446

Is that something that addressed here?
Ansible, Docker out of EPEL and docker-py from pip

ansible 1.8.2
Docker version 1.3.2, build 39fa2fa/1.3.2
docker-py (0.7.0)

**Comment by abadger** [comment]
Does specifying  docker_api_version for your task fix things?

Like:

```
tasks:
  - docker:
      docker_api_version:1.15
      [...]
```

**Comment by apenney** [comment]
I have the same problem and this fixed it perfectly for me, just in case that's helpful!

**Comment by tfhartmann** [comment]
@abadger Yup! That helped!

**Comment by abadger** [comment]
Excellent :-).  I'll paste the list information here in case there's any further difficulties with this.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by tfhartmann** [comment]
@abadger  I think that thats a decent work around, but it still seems like a bug no?  That functionally makes the docker_api_version a required parameter to the module doesn't it?

**Comment by abadger** [comment]
Ah, let me explain that part :-)

docker has both a client and a server.  The server is the docker daemon that runs on the host system.  The client is the docker-py python library.  These can be updated independently of each other.  Since docker is a pretty quickly advancing target, the docker API can change when these update.  for some reason (I'm not involved with docker-py development so I don't know if there's a technical reason for this) docker-py doesn't autodetect the api version of the server it's connecting to and adjust itself accordingly.  Code that uses docker-py can manually set the APIVersion to match, though.

For people running ansible this means that you could have a mismatch between docker-py and the docker server where docker-py's default ApiVersion is different than the docker server's ApiVersion.  When that happens you can either update or downgrade one of those packages to make their ApiVersions match or (if docker-py supports the server's ApiVersion, it just isn't the default) you can tell ansible the server's ApiVersion so ansible can then tell docker-py which ApiVersion to use.

Hope that helps explain why ansible does things the way it does here.  (And if you can figure out a way to get docker-py to autodetect the best server ApiVersion, I could certainly look at reviewing a pull request to implement that ;-)

**Comment by tfhartmann** [comment]
@abadger  Thanks for the explanation thats really helpful!
