### ISSUE TITLE
Docker: ENV doesn't work with an existing container

### ISSUE THREAD

**Issue by apenney** [ansible/ansible-modules-core#719]
I ran into a weird bug today, using:

ansible 1.8.2
Docker version 1.3.2, build 39fa2fa/1.3.2 (centos 7)
docker-py (0.7.1)

If a container has been made with ansible without any 'env' key any attempt to add envs causes it to reuse the existing container and it doesn't pass in the new envs.  I had to manually:

$ docker rm containerid

Then rerun ansible to get it to create the container as expected.  Other people have expressed similar problems on IRC:

[13:52:25]  <KannOx>    in my experience with docker, there's a bunch of things that won't take effect unless you delete and recreate
[13:52:32]  <KannOx>    *with docker via ansible
[13:52:54]  <KannOx>    most importantly envs, volumes and ports
[13:53:29]  <halberom>  perhaps you need a method of checking a running docker state, and if necessary, del and re-create it.
[13:53:44]  <halberom>  not sure what state output you can get

Maybe we should simply delete and recreate if you're passing in an env/volume/port due to this problem?  This took me several hours to debug!

**Comment by daviddyball** [comment]
I dont think this is a module issue, it's the way dockers Client API works. In normal docker it isn't possible to add environment variables to an already existing container.

Currently the logic in the docker module really only cares whether a) the container with `name` exists b) said container is running off of `image` and c) the container is in `state`. 

There are no checks to match any other args in the spec.

There are two approaches:
1. Make the module implicitly strict, whereby it will expect the container to be in _exactly_ the state specified, otherwise it will destroy the current container and recreate it to match, or
2. Add a bool argument like `enforce` to it so you can choose to enable strict states.

Not sure what the maintainers stance is on destructive vs. least-destructive behaviour though.

As an aside, there are quite a few things the current docker module doesn't do that I'd expect. I've started a thread on the dev mailing-list, so hopefully I can get some direction and start making PRs

**Comment by abadger** [comment]
If you're able to try out the docker module from the devel branch, does state=reloaded from this merged pull request  https://github.com/ansible/ansible-modules-core/pull/502 do what you need?

**Comment by abadger** [comment]
Closing ticket, Feature should be implemented in current and devel and stable-1.9 branches as per #502

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
