### ISSUE TITLE
docker-py module:  leaves domainname empty 

### ISSUE THREAD

**Issue by Ariel-Lieberman** [ansible/ansible-modules-core#764]
When one creates a container with the docker client and specifies _hostname=host.domain_ docker sets the Hostname to _host_ and Domainname to _domain_.

The Problem:
However, docker-py sets the Hostname to _"host.domain"_ and leaves the Domainname empty.

One can test it using the _docker inspect_ command.

The fix should be easy.  In the create_containers split by the first '.' and set the hostname and domainname parameters.

**Comment by tpaz** [comment]
+1, but after reading both Ansible docker module code and docker-py, it seems more elegant to simply add the "domainname" parameter (keyword argument in code) to Ansible module rather than changing docker-py which isn't part of this open source project anyway. 
Pros: 
  will be consistent with docker-py implementation and straight froward delegation of call to create_container funciton(**kwargs)
Cons:
  will not be consistent with Docker run arguments

The latter (Cons) seems less of concern to me, as probably docker-py had a good reason to separate hostname and domain name parameters while docker run original CLI simply didn't.

When using schematic approach for orchestration (e.g. .yaml or json) with metadata, it actually seems more reasonable (flexible) to separate domain name and hostname. 
So I would prefer adding domain name to ansible module as parameter rather than patching docker-py to parse FQDN from hostname.

I will try a pull request for our solution: https://github.com/tpaz/ansible-modules-core/blob/devel/cloud/docker/docker.py

**Comment by abadger** [comment]
@Ariel-Lieberman I think @tpaz's reasoning is sound but I don't use docker regularly.  Do you think that having domainname as a separate parameter makes sense?  If so, I'll merge pull request #769  to fix this issue.

**Comment by Ariel-Lieberman** [comment]
I'm OK with @tpaz solution.  The other way is to have logic to split the host-name behind the seen (as the docker CLI does.)  @tpaz looks more clean.

**Comment by abadger** [comment]
Cool.  Merged 764.

**Comment by tpaz** [comment]
thanks
