### ISSUE TITLE
file module recursive mode incorrectly sets file permissions

### ISSUE THREAD

**Issue by shepdelacreme** [ansible/ansible-modules-core#778]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.8.2
  configured module search path = None
```
##### Environment:

Control Machine: OS X 10.10.2
Target Machine: RHEL 6.6
##### Summary:

When trying to recursively set file mode using symbolic format the ansible file module will incorrectly set permissions on some files. Specifically I experienced this issue when trying to ensure that all files in /usr/bin have 755 or less permissive permissions set. To do this you should be able to say "mode=go-w". This should remove write perms from group and other for any file in /usr/bin. However this does not work on certain files. i.e.

/usr/bin/sudo
/usr/bin/sudoreplay
##### Steps To Reproduce:

Check permissions of files in /usr/bin before running commands:

```
# ls -la /usr/bin/sudo
---s--x--x. 1 root root 123832 Jul 31  2014 /usr/bin/sudo
```

Run either of the following commands:

```
- hosts: all
  sudo: yes

  tasks:
    - name: Set file perms recursively
      file: path=/usr/bin owner=root mode=go-w recurse=yes
```

```
ansible -i hosts -m file --args="path=/usr/bin owner=root recurse=yes mode=go-w" -u ec2-user --sudo
```
##### Expected Results:

This above commands should do nothing against a default /usr/bin/sudo file. If you add group or other write permissions before running the above commands then those write permissions should be removed. To see the expected results run the above command against a single file.
##### Actual Results:

Check permissions after running above commands:

```
# ls -la /usr/bin/sudo
-rwxr-xr-x. 1 root root 123832 Jul 31  2014 /usr/bin/sudo
```

Fix sudo so the box isn't completely hosed:

```
# chmod 4111 /usr/bin/sudo
```

**Comment by abadger** [comment]
This seems to be a problem with symlinks and recursively setting file permissions.  If there's only one file in the directory everything is fine even if it has the same permissions of sudo.  When we add a symlink to sudo into the directory the present code looks at the permissions of the symlink (always 0777 on Linux) calculates the new permissions and then applies that to the symlink (which on Linux ends up applying the permissions to the file that's the target of the symlink).  I have some code to make ansible attempt to change the value of the symlink but keep the link target the same.  Before pushing that I'm evaluating whether we should be handling the module's follow parameter as well.

**Comment by abadger** [comment]
Proposed new test cases that define how file should work when symlinks and recursive are involved: https://gist.github.com/abadger/3277c8632ee3a34dd1dc

**Comment by abadger** [comment]
Okay, I think those commits ought to fix this issue.  What happens now is:
- In general when we encounter a symlink, if follow=False we make sure that we have not changed the permissions of the file pointed to by the symlink.
- If follow=True, then we find the file being pointed to, get its permissions, and change that to the new permissions.
- With recurse=True and follow=True, anytime we encounter a symlink to a directory we both modify permissions on the symlink and the directory.  Then we recurse into the directory to modify permissions on the contained files as well. 

The first two behaviour changes should be enough to fix this issue (the specific issue and other, similar ways in which it could be encountered.).

Thanks for pointing out the problem!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
