### ISSUE TITLE
Apt module hangs unexpectedly (without apt going interactive)

### ISSUE THREAD

**Issue by ABAJosh** [ansible/ansible-modules-core#78]
Template time!
##### Issue Type:

Bug Report
##### Ansible Version:

deploy@mail2:/home/josh$ ansible --version
ansible 1.7.2
##### Environment:

Ubuntu 14.04
##### Summary:

The apt module hangs when upgrading packages. 
##### Steps To Reproduce:

Playbook:
     - name: update cache
       apt: "update_cache=yes"
- name: upgrade packages
   apt: upgrade=safe

The issue also occurs when running upgrade=yes, and when running via ansible directly:
ansible all -s -m apt -a "update_cache=yes upgrade=yes"
##### Expected Results:

Packages are upgraded and the playbook continues, or the ansible command terminates
##### Actual Results:

Playbook never moves to the next step, or the ansible module never terminates. This occurs even when there are no packages to upgrade, so it should not be going interactive.

**Comment by zpatten** [comment]
I'm running into the same issue as well.

```
$ ansible --version
ansible 1.7.2
```

**Comment by jimi-c** [comment]
I believe this is the same issue as #31, which I just fixed. Could you please try again using the latest version from devel and let us know if the problem continues to show up in your use case?

Thanks!

**Comment by ABAJosh** [comment]
I can confirm that in my environment, this issue is resolved. I tested with the ansible-playbook and ansible commands listed in the original post.

Thanks! 

Version info:
ansible --version
ansible 1.8 (devel fa953e162e) last updated 2014/11/11 15:03:40 (GMT -400)

**Comment by jimi-c** [comment]
@ABAJosh excellent, we'll go ahead and close this issue then.

If you or anyone else continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
