### ISSUE TITLE
  /bin/sh: Ileagal instruction (coredump) when trying to use copy module with AIX

### ISSUE THREAD

**Issue by cmlsharp** [ansible/ansible-modules-core#80]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7 (devel 75e5b6401c) last updated 2014/07/22 14:37:30 (GMT -400)
##### Environment:

RHEL 6 managing AIX
##### Summary:

Ansible fails when using copy module on AIX
##### Steps To Reproduce:

Attempt to copy file to AIX with Python 2.7.8 using copy module
##### Expected Results:

The file copies successfully 
##### Actual Results:

```
<fdb> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO fdb
<fdb> EXEC /bin/sh -c 'rc=0; [ -r "/testfile" ] || rc=2; [ -f "/testfile" ] || rc=1; [ -d "/testfile" ] && echo 3 && exit 0; (/usr/bin/md5sum /testfile 2>/dev/null) || (/sbin/md5sum -q /testfile 2>/dev/null) || (/usr/bin/digest -a md5 /testfile 2>/dev/null) || (/sbin/md5 -q /testfile 2>/dev/null) || (/usr/bin/md5 -n /testfile 2>/dev/null) || (/bin/md5 -q /testfile 2>/dev/null) || (/usr/bin/csum -h MD5 /testfile 2>/dev/null) || (/bin/csum -h MD5 /testfile 2>/dev/null) || (echo "${rc} /testfile")'
<fdb> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1406560163.65-86612973678860 && echo $HOME/.ansible/tmp/ansible-tmp-1406560163.65-86612973678860'
<fdb> PUT /testfile TO /home/root/.ansible/tmp/ansible-tmp-1406560163.65-86612973678860/source
<fdb> PUT /tmp/tmpcKn29o TO /home/root/.ansible/tmp/ansible-tmp-1406560163.65-86612973678860/copy
<fdb> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/local/python/python /home/root/.ansible/tmp/ansible-tmp-1406560163.65-86612973678860/copy; rm -rf /home/root/.ansible/tmp/ansible-tmp-1406560163.65-86612973678860/ >/dev/null 2>&1'
fdb | FAILED >> {
    "failed": true,
    "md5sum": "d41d8cd98f00b204e9800998ecf8427e",
    "msg": "/bin/sh: 5046336 Illegal instruction(coredump)\n",
    "parsed": false
}
```

Copied from [here](https://github.com/ansible/ansible/issues/8310#event-171718069)

**Comment by abadger** [comment]
So, reading the former ticket's comments, there's two ways we could go with this:
- This is a problem with the version of python you have installed.  Have the vendor fix it or compile your own.
- Or: ansible tries to detect AIX and if found we use some other hashing strategy (since this is a file, we might be able to call out to /usr/bin/md5sum on AIX if AIX has that utility standard.)

Both of these have drawbacks: For the first case we're relying on the vendor to fix their issue.  In the latter case, we'd 1) have to depend on further dependencies being installed/available on AIX and 2) hashlib is so useful that we'll likely to be using it in other places that won't be so easy to work around.

**Comment by cmlsharp** [comment]
I did indeed compile this version of python myself. I'm inclined to think it is the latter. However, openssl (which provides hashlib IIRC) was installed. I read somewhere that symlinking /bin/md5sum with /bin/csum should work. Oddly enough It worked on one of the AIX servers but not the other. It is very possible it was compiled with the wrong openssl library on the second server. Although to be honest, as my summer internship there has ended, I no longer have the servers in front of me.

**Comment by abadger** [comment]
<nod>  I'm going to close this for now since you aren't running AIX anymore and no one else using it has chimed in on this new bug.  From the reports, it seems like the official python package for AIX from IBM is known to contain a bug which causes this whenever attempting to hash a string.  Various third parties are reported to provide working python packages (for instance, http://www.perzl.org/aix/index.php?n=Main.Python ) so there is a workaround if it's causing difficulties.

If there are some AIX people keeping track of this silently, we'd be happy to look at a Pull Request to fix it.  The ansible code has a few places that are creating checksums.  The Pull Request would need to modify those to use an alternate method of obtaining the checksum (currently using sha1s).
