### ISSUE TITLE
Git submodule does not show the error message

### ISSUE THREAD

**Issue by abrahammartin** [ansible/ansible-modules-core#81]
Original issue: https://github.com/ansible/ansible/issues/8596
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.7.1
##### Environment:

N/A
##### Summary:

I had a wrong permission in one of the files inside my .git folder but the git submodule didn't show the error message, only a very generic "msg: Failed to download remote objects and refs". I believe that the git submodule should show the error message that git is showing, so you do not have to log in and execute the command by yourself to check the error and see what happened.
##### Steps To Reproduce:

Just change the permissions of some files inside the .git to some that the ansible user cannot read/write
##### Expected Results:

The actual error
##### Actual Results:

"msg: Failed to download remote objects and refs"

**Comment by abadger** [comment]
That commit should add the message from git to the return value.  thanks for reporting!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
