### ISSUE TITLE
Cannot use urls with yum and rpm_key modules on CentOS 5

### ISSUE THREAD

**Issue by JorisVanEijden** [ansible/ansible-modules-core#826]
Yum on RHEL 5 and CentOS 5 does not support installing from urls.
It returns "nothing to do" with a code of 0, making ansible think the package is already installed.

Please either document this at the relevant module pages or make ansible detect and error on this case.

I believe this affects both the yum and the rpm_key modules.

This is a reopening of the previous ansible issue https://github.com/ansible/ansible/issues/5327

**Comment by Jmainguy** [comment]
@JorisVanEijden give #1408 a shot. It fails on CentOS 5 now.

**Comment by JorisVanEijden** [comment]
I checked and tested and it works.
Hope to see this in a future release.

I also noticed that I was wrong about the rpm_key. That does work with urls.

**Comment by abadger** [comment]
Merged to devel and also to the stable-1.9 branch.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
