### ISSUE TITLE
NameError: name 'sys' is not defined

### ISSUE THREAD

**Issue by greenscar** [ansible/ansible-modules-core#994]
osx 10.10.2
Python 2.7.9
ansible 1.8.4

I create a script & call it exit.py

```
#!/usr/bin/python
import sys
print "test"
sys.exit(0)
```

and I execute in ansible via:

```
- debug: msg="test"

- name: shell
  shell: python --version

- name: test script
  script: ../../../exit.py

- name: launch ansible cloudformation c
  cloudformation:
    stack_name: "ansible-cloudformation"
    state: "present"
    region: "us-east-1"
    disable_rollback: true
    template: "files/cloudformation-example.json"
    template_parameters:
      KeyName: "jmartin"
      DiskType: "ephemeral"
      InstanceType: "m1.small"
      ClusterSize: 3
    tags:
      Stack: "ansible-cloudformation"

```

Exit works fine but cloudformation barfs with sys not defined.

```
__
| ~/workspaces/github/ansible @ macmini (james) 
| => ansible-playbook -i envs/localhost ./tasks/aws_test.yml -vvvv 

PLAY [localhost] ************************************************************** 

TASK: [debug msg="test"] ****************************************************** 
ok: [localhost] => {
    "msg": "test"
}

TASK: [shell] ***************************************************************** 
<localhost> 
<localhost> 
<localhost> 
<localhost> u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/james/.ansible/tmp/ansible-tmp-1427249652.83-278423677659105/command; rm -rf /Users/james/.ansible/tmp/ansible-tmp-1427249652.83-278423677659105/ >/dev/null 2>&1']
changed: [localhost] => {"changed": true, "cmd": "python --version", "delta": "0:00:00.012900", "end": "2015-03-24 19:14:12.953713", "rc": 0, "start": "2015-03-24 19:14:12.940813", "stderr": "Python 2.7.9", "stdout": "", "warnings": []}

TASK: [test script] *********************************************************** 
<localhost> 
<localhost> 
<localhost> 
<localhost> LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
<localhost> 
changed: [localhost] => {"changed": true, "rc": 0, "stderr": "", "stdout": "test\n"}

TASK: [launch ansible cloudformation c] *************************************** 
<localhost> stack_name=ansible-cloudformation state=present region=us-east-1 template=files/cloudformation-example.json
<localhost> 
<localhost> 
<localhost> u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/james/.ansible/tmp/ansible-tmp-1427249653.04-170310297715723/cloudformation; rm -rf /Users/james/.ansible/tmp/ansible-tmp-1427249653.04-170310297715723/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "parsed": false}
failed=True msg='boto required for this module'
Traceback (most recent call last):
  File "/Users/james/.ansible/tmp/ansible-tmp-1427249653.04-170310297715723/cloudformation", line 122, in <module>
    sys.exit(1)
NameError: name 'sys' is not defined


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/james/aws_test.retry

localhost                  : ok=3    changed=2    unreachable=0    failed=1   


```

**Comment by abadger** [comment]
> failed: [localhost] => {"failed": true, "parsed": false}
> failed=True msg='boto required for this module'

Looking at this portion of the error message, I wonder if the boto error is
putting things in some cornercase which makes unavailable.  Could you try
installing the boto python module and seeing if one or both of the problems
disappear?

**Comment by greenscar** [comment]
Thanks @abadger; my apologies for not being clear on that initially. I saw that error & installed & still got the same error..

```
________________________________________________________________________________
| ~/workspaces/github/ansible @ macmini (james) 
| => pip install boto
Collecting boto
  Downloading boto-2.36.0-py2.py3-none-any.whl (1.3MB)
    100% |################################| 1.3MB 255kB/s 
Installing collected packages: boto

Successfully installed boto-2.36.0
________________________________________________________________________________
| ~/workspaces/github/ansible @ macmini (james) 
| => ansible-playbook -i envs/localhost ./tasks/aws_test.yml -vvvv 

PLAY [localhost] ************************************************************** 

TASK: [debug msg="test"] ****************************************************** 
ok: [localhost] => {
    "msg": "test"
}
TASK: [shell] ***************************************************************** 
<localhost> 
<localhost> 
<localhost> 
<localhost> u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/james/.ansible/tmp/ansible-tmp-1427295367.3-93991491652449/command; rm -rf /Users/james/.ansible/tmp/ansible-tmp-1427295367.3-93991491652449/ >/dev/null 2>&1']
changed: [localhost] => {"changed": true, "cmd": "python --version", "delta": "0:00:00.018870", "end": "2015-03-25 07:56:07.554478", "rc": 0, "start": "2015-03-25 07:56:07.535608", "stderr": "Python 2.7.9", "stdout": "", "warnings": []}

TASK: [test script] *********************************************************** 
<localhost> 
<localhost> 
<localhost> 
<localhost> LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
<localhost> 
changed: [localhost] => {"changed": true, "rc": 0, "stderr": "", "stdout": "test\n"}

TASK: [launch ansible cloudformation c] *************************************** 
<localhost> stack_name=ansible-cloudformation state=present region=us-east-1 template=files/cloudformation-example.json
<localhost> 
<localhost> 
<localhost> u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/james/.ansible/tmp/ansible-tmp-1427249360.15-81561235976354/cloudformation; rm -rf /Users/james/.ansible/tmp/ansible-tmp-1427249360.15-81561235976354/ >/dev/null 2>&1']
failed: [localhost] => {"failed": true, "parsed": false}
failed=True msg='boto required for this module'
Traceback (most recent call last):
  File "/Users/james/.ansible/tmp/ansible-tmp-1427249360.15-81561235976354/cloudformation", line 122, in <module>
    sys.exit(1)
NameError: name 'sys' is not defined


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/james/aws_test.retry

localhost                  : ok=2    changed=1    unreachable=0    failed=1   

________________________________________________________________________________
| ~/workspaces/github/ansible @ macmini (james) 
| => ansible --version
ansible 1.8.4
  configured module search path = None
```

**Comment by greenscar** [comment]
In case it may help, this script is located via **git@github.com:sandlinjames/ansible.git** branch name: **Stelligent**

FYI: I removed ansible & boto then rebooted then reinstalled & still get the same error. 

However, if I checkout the repo on my laptop (OSX 10.9.5) and execute it gets past this point. 

Looks like I'm not alone in this error
https://groups.google.com/forum/#!msg/ansible-project/ftlmfIC1DHk/ZAQ9Nj4xPLsJ

and a but in ansible which was closed and shouldn't have been: 
https://github.com/ansible/ansible/issues/5734

Per the second link, this "fixes" the issue. In reality it just creates a workaround.
export PYTHONPATH="/usr/local/lib/python2.7/site-packages"

After adding this export to my profile, I am past this problem. This should either be added in Ansible setup instructions for future users or should be resolved in the tool itself.

**Comment by bcoca** [comment]
looks like the cloudformation module needs an 'import sys', but it should have that already from importing the shared basic.py

**Comment by abadger** [comment]
The reason the import sys from basic.py isn't affecting this code is that basic.py is getting inserted at the bottom of this code instead of at the top.  The correct fix, however, is to use module.fail_json() inside of main() instead of sys.exit() at the toplevel.  The commit I just pushed should do that.

However, there is one more potential problem.  From your error, I think that the module still won't be able to import boto.  If you could just let us know whether it works or not (and if not, what the new symptoms are/what your test script does if you replace import sys with import boto) that would be helpful.  (And if I'm wrong and the cloudformation module simply starts working with that change then even better.  You can just close this ticket if that's the case ;-)

**Comment by steenzout** [comment]
@abadger what about ec2_key.py?

```
$ pwd
/.../env/lib/python2.7/site-packages/ansible/modules/core/cloud/amazon

# modules that import sys
$ grep 'import sys' *
ec2.py:import sys
ec2_ami.py:import sys
ec2_asg.py:import sys
ec2_elb.py:import sys
ec2_elb_lb.py:import sys
ec2_lc.py:import sys
ec2_metric_alarm.py:import sys
ec2_scaling_policy.py:import sys
ec2_snapshot.py:import sys
ec2_tag.py:import sys
ec2_vol.py:import sys
ec2_vpc.py:import sys
elasticache.py:import sys
rds.py:import sys
rds_param_group.py:import sys
rds_subnet_group.py:import sys
route53.py:import sys
s3.py:import sys

# ec2_key doesn't import sys but does it call it? yes...
$ grep 'sys.exit' ec2_key.py
sys.exit(1)
```

for me it's throwing the same `sys` error which makes sense since it's not importing `sys`.
also if using `HAS_BOTO` is the way to go then you would need to patch the rest of the other ec2 modules, no?

apart from the error message, in my case I know `boto` is installed on the virtualenv I'm using so I've added `import sys` by hand in `ec2_key.py` (which is where I'm getting the problem) and now the error message changed from "sys is not defined" to "boto required for this module" as expected.
this an improvement but something else is broken since using the python interpreter for the virtualenv being used to run the ansible playbook I run "import boto" and it works.
Here are my steps...

| name | version |
| --- | --- |
| python | 2.7.9 |
| ansible | 1.8.2 |

```
$ which python
/.../env/bin/python

$ python
Python 2.7.9 (default, Dec 13 2014, 15:13:49) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto.ec2
>>> import ansible.modules.core.cloud.amazon.ec2_key
{"msg": "this module requires key=value arguments (['<<INCLUDE_ANSIBLE_MODULE_ARGS>>'])", "failed": true}

$ echo $?
1
```

**Comment by steenzout** [comment]
if I add the `HAS_BOTO` patch to `ec2_key.py` as well the import continues to fail.

**Comment by steenzout** [comment]
disregard my comment, doing a direct import will fail because you need to pass arguments to load the module.

**Comment by steenzout** [comment]
I've changed the header of `ec2_key.py` from `#!/usr/bin/python` to `#!/usr/bin/env python` and the module started working.
If I leave the module header as it is it will not load my virtualenv to `sys.path` since I'm using the `python27` interpreter from virtualenv `/Users/someone/path_to/env/bin/python`.

**Comment by memelet** [comment]
I'm getting this error for ec2_group.py. But I don't understand at all. I have been running this play on this workstation with this version of ansible for weeks. It's only this mornning that I get this error.

I am seeing this with both 1.9.1 and 1.9.2

```
failed: [localhost] => {"failed": true, "parsed": false}
failed=True msg='boto required for this module'
Traceback (most recent call last):
  File "/Users/bkaplan/.ansible/tmp/ansible-tmp-1433559288.66-127589512702269/ec2_group", line 114, in <module>
    sys.exit(1)
NameError: name 'sys' is not defined
```

**Comment by memelet** [comment]
exporting ...

```
export PYTHONPATH="/usr/local/lib/python2.7/site-packages"
```

... resolve this on osx. But why was this needed today but not yesterday?

**Comment by abadger** [comment]
Just doing some record keeping and then closing this:
- steenzout fixed the ec2_key.py module problem that he discovered above via a different pull request.  
- The errors that are being resolved by setting PYTHONPATH and/or /usr/bin/env python are likely due to having two versions of python on the system.  boto is being installed into one version (the one that's being pointed to by PYTHONPATH or that env is picking as the first one) while ansible is using the second one (usually the one in /usr/bin/ansible).  The most correct way to resolve this situatoin is to tell ansible the correct python interpreter to use.  For instance, if you have a host named osx-server in your inventory file, then change the line in inventory to:

```
osx-server ansible_python_interpreter=/usr/local/bin/python
```
